/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ModuloAssinaturaResultado"
 * 	found in "../../../asn/assinatura.asn1"
 * 	`asn1c -fline-refs -fcompound-names -fincludes-quoted`
 */

#ifndef	_AlgoritmoHash_H_
#define	_AlgoritmoHash_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeEnumerated.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum AlgoritmoHash {
	AlgoritmoHash_sha1	= 1,
	AlgoritmoHash_sha256	= 2,
	AlgoritmoHash_sha384	= 3,
	AlgoritmoHash_sha512	= 4
} e_AlgoritmoHash;

/* AlgoritmoHash */
typedef long	 AlgoritmoHash_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_AlgoritmoHash_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_AlgoritmoHash;
extern const asn_INTEGER_specifics_t asn_SPC_AlgoritmoHash_specs_1;
asn_struct_free_f AlgoritmoHash_free;
asn_struct_print_f AlgoritmoHash_print;
asn_constr_check_f AlgoritmoHash_constraint;
ber_type_decoder_f AlgoritmoHash_decode_ber;
der_type_encoder_f AlgoritmoHash_encode_der;
xer_type_decoder_f AlgoritmoHash_decode_xer;
xer_type_encoder_f AlgoritmoHash_encode_xer;
jer_type_encoder_f AlgoritmoHash_encode_jer;
oer_type_decoder_f AlgoritmoHash_decode_oer;
oer_type_encoder_f AlgoritmoHash_encode_oer;
per_type_decoder_f AlgoritmoHash_decode_uper;
per_type_encoder_f AlgoritmoHash_encode_uper;
per_type_decoder_f AlgoritmoHash_decode_aper;
per_type_encoder_f AlgoritmoHash_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _AlgoritmoHash_H_ */
#include "asn_internal.h"
