/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ModuloAssinaturaResultado"
 * 	found in "../../../asn/assinatura.asn1"
 * 	`asn1c -fline-refs -fcompound-names -fincludes-quoted`
 */

#ifndef	_AlgoritmoHashInfo_H_
#define	_AlgoritmoHashInfo_H_


#include "asn_application.h"

/* Including external dependencies */
#include "AlgoritmoHash.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* AlgoritmoHashInfo */
typedef struct AlgoritmoHashInfo {
	AlgoritmoHash_t	 algoritmo;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} AlgoritmoHashInfo_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_AlgoritmoHashInfo;
extern asn_SEQUENCE_specifics_t asn_SPC_AlgoritmoHashInfo_specs_1;
extern asn_TYPE_member_t asn_MBR_AlgoritmoHashInfo_1[1];

#ifdef __cplusplus
}
#endif

#endif	/* _AlgoritmoHashInfo_H_ */
#include "asn_internal.h"
