/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ModuloAssinaturaResultado"
 * 	found in "../../../asn/assinatura.asn1"
 * 	`asn1c -fline-refs -fcompound-names -fincludes-quoted`
 */

#ifndef	_AlgoritmoAssinatura_H_
#define	_AlgoritmoAssinatura_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeEnumerated.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum AlgoritmoAssinatura {
	AlgoritmoAssinatura_rsa	= 1,
	AlgoritmoAssinatura_ecdsa	= 2,
	AlgoritmoAssinatura_cepesc	= 3
} e_AlgoritmoAssinatura;

/* AlgoritmoAssinatura */
typedef long	 AlgoritmoAssinatura_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_AlgoritmoAssinatura_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_AlgoritmoAssinatura;
extern const asn_INTEGER_specifics_t asn_SPC_AlgoritmoAssinatura_specs_1;
asn_struct_free_f AlgoritmoAssinatura_free;
asn_struct_print_f AlgoritmoAssinatura_print;
asn_constr_check_f AlgoritmoAssinatura_constraint;
ber_type_decoder_f AlgoritmoAssinatura_decode_ber;
der_type_encoder_f AlgoritmoAssinatura_encode_der;
xer_type_decoder_f AlgoritmoAssinatura_decode_xer;
xer_type_encoder_f AlgoritmoAssinatura_encode_xer;
jer_type_encoder_f AlgoritmoAssinatura_encode_jer;
oer_type_decoder_f AlgoritmoAssinatura_decode_oer;
oer_type_encoder_f AlgoritmoAssinatura_encode_oer;
per_type_decoder_f AlgoritmoAssinatura_decode_uper;
per_type_encoder_f AlgoritmoAssinatura_encode_uper;
per_type_decoder_f AlgoritmoAssinatura_decode_aper;
per_type_encoder_f AlgoritmoAssinatura_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _AlgoritmoAssinatura_H_ */
#include "asn_internal.h"
