/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ModuloAssinaturaResultado"
 * 	found in "../../../asn/assinatura.asn1"
 * 	`asn1c -fline-refs -fcompound-names -fincludes-quoted`
 */

#ifndef	_AssinaturaDigital_H_
#define	_AssinaturaDigital_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"
#include "OCTET_STRING.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* AssinaturaDigital */
typedef struct AssinaturaDigital {
	long	 tamanho;
	OCTET_STRING_t	 hash;
	OCTET_STRING_t	 assinatura;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} AssinaturaDigital_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_AssinaturaDigital;
extern asn_SEQUENCE_specifics_t asn_SPC_AssinaturaDigital_specs_1;
extern asn_TYPE_member_t asn_MBR_AssinaturaDigital_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _AssinaturaDigital_H_ */
#include "asn_internal.h"
