/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ModuloAssinaturaResultado"
 * 	found in "../../../asn/assinatura.asn1"
 * 	`asn1c -fline-refs -fcompound-names -fincludes-quoted`
 */

#include "AssinaturaArquivo.h"

asn_TYPE_member_t asn_MBR_AssinaturaArquivo_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct AssinaturaArquivo, nomeArquivo),
		(ASN_TAG_CLASS_UNIVERSAL | (27 << 2)),
		0,
		&asn_DEF_GeneralString,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"nomeArquivo"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct AssinaturaArquivo, assinatura),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_AssinaturaDigital,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"assinatura"
		},
};
static const ber_tlv_tag_t asn_DEF_AssinaturaArquivo_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_AssinaturaArquivo_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 1, 0, 0 }, /* assinaturaat 75 */
    { (ASN_TAG_CLASS_UNIVERSAL | (27 << 2)), 0, 0, 0 } /* nomeArquivoat 73 */
};
asn_SEQUENCE_specifics_t asn_SPC_AssinaturaArquivo_specs_1 = {
	sizeof(struct AssinaturaArquivo),
	offsetof(struct AssinaturaArquivo, _asn_ctx),
	asn_MAP_AssinaturaArquivo_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_AssinaturaArquivo = {
	"AssinaturaArquivo",
	"AssinaturaArquivo",
	&asn_OP_SEQUENCE,
	asn_DEF_AssinaturaArquivo_tags_1,
	sizeof(asn_DEF_AssinaturaArquivo_tags_1)
		/sizeof(asn_DEF_AssinaturaArquivo_tags_1[0]), /* 1 */
	asn_DEF_AssinaturaArquivo_tags_1,	/* Same as above */
	sizeof(asn_DEF_AssinaturaArquivo_tags_1)
		/sizeof(asn_DEF_AssinaturaArquivo_tags_1[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_AssinaturaArquivo_1,
	2,	/* Elements count */
	&asn_SPC_AssinaturaArquivo_specs_1	/* Additional specs */
};

