/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ModuloAssinaturaResultado"
 * 	found in "../../../asn/assinatura.asn1"
 * 	`asn1c -fline-refs -fcompound-names -fincludes-quoted`
 */

#ifndef	_AssinaturaArquivo_H_
#define	_AssinaturaArquivo_H_


#include "asn_application.h"

/* Including external dependencies */
#include "GeneralString.h"
#include "AssinaturaDigital.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* AssinaturaArquivo */
typedef struct AssinaturaArquivo {
	GeneralString_t	 nomeArquivo;
	AssinaturaDigital_t	 assinatura;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} AssinaturaArquivo_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_AssinaturaArquivo;
extern asn_SEQUENCE_specifics_t asn_SPC_AssinaturaArquivo_specs_1;
extern asn_TYPE_member_t asn_MBR_AssinaturaArquivo_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _AssinaturaArquivo_H_ */
#include "asn_internal.h"
