/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ModuloAssinaturaResultado"
 * 	found in "../../../asn/assinatura.asn1"
 * 	`asn1c -fline-refs -fcompound-names -fincludes-quoted`
 */

#ifndef	_Assinatura_H_
#define	_Assinatura_H_


#include "asn_application.h"

/* Including external dependencies */
#include "asn_SEQUENCE_OF.h"
#include "constr_SEQUENCE_OF.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct AssinaturaArquivo;

/* Assinatura */
typedef struct Assinatura {
	struct Assinatura__arquivosAssinados {
		A_SEQUENCE_OF(struct AssinaturaArquivo) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} arquivosAssinados;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Assinatura_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Assinatura;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "AssinaturaArquivo.h"

#endif	/* _Assinatura_H_ */
#include "asn_internal.h"
