/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ModuloAssinaturaResultado"
 * 	found in "../../../asn/assinatura.asn1"
 * 	`asn1c -fline-refs -fcompound-names -fincludes-quoted`
 */

#include "AutoAssinaturaDigital.h"

asn_TYPE_member_t asn_MBR_AutoAssinaturaDigital_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct AutoAssinaturaDigital, usuario),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_DescritorChave,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"usuario"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct AutoAssinaturaDigital, algoritmoHash),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_AlgoritmoHashInfo,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"algoritmoHash"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct AutoAssinaturaDigital, algoritmoAssinatura),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_AlgoritmoAssinaturaInfo,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"algoritmoAssinatura"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct AutoAssinaturaDigital, assinatura),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_AssinaturaDigital,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"assinatura"
		},
};
static const ber_tlv_tag_t asn_DEF_AutoAssinaturaDigital_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_AutoAssinaturaDigital_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 0, 0, 3 }, /* usuarioat 86 */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 1, -1, 2 }, /* algoritmoHashat 87 */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 2, -2, 1 }, /* algoritmoAssinaturaat 88 */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 3, -3, 0 } /* assinaturaat 90 */
};
asn_SEQUENCE_specifics_t asn_SPC_AutoAssinaturaDigital_specs_1 = {
	sizeof(struct AutoAssinaturaDigital),
	offsetof(struct AutoAssinaturaDigital, _asn_ctx),
	asn_MAP_AutoAssinaturaDigital_tag2el_1,
	4,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_AutoAssinaturaDigital = {
	"AutoAssinaturaDigital",
	"AutoAssinaturaDigital",
	&asn_OP_SEQUENCE,
	asn_DEF_AutoAssinaturaDigital_tags_1,
	sizeof(asn_DEF_AutoAssinaturaDigital_tags_1)
		/sizeof(asn_DEF_AutoAssinaturaDigital_tags_1[0]), /* 1 */
	asn_DEF_AutoAssinaturaDigital_tags_1,	/* Same as above */
	sizeof(asn_DEF_AutoAssinaturaDigital_tags_1)
		/sizeof(asn_DEF_AutoAssinaturaDigital_tags_1[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_AutoAssinaturaDigital_1,
	4,	/* Elements count */
	&asn_SPC_AutoAssinaturaDigital_specs_1	/* Additional specs */
};

