/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ModuloBU"
 * 	found in "../../../asn/bu.asn1"
 * 	`asn1c -fline-refs -fcompound-names -fincludes-quoted`
 */

#ifndef	_DadosSA_H_
#define	_DadosSA_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"
#include "ModuloBU_NumeroInternoUrna.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* DadosSA */
typedef struct DadosSA {
	long	 juntaApuradora;
	long	 turmaApuradora;
	ModuloBU_NumeroInternoUrna_t	*numeroInternoUrnaOrigem;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DadosSA_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DadosSA;
extern asn_SEQUENCE_specifics_t asn_SPC_DadosSA_specs_1;
extern asn_TYPE_member_t asn_MBR_DadosSA_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _DadosSA_H_ */
#include "asn_internal.h"
