/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ModuloBU"
 * 	found in "../../../asn/bu.asn1"
 * 	`asn1c -fline-refs -fcompound-names -fincludes-quoted`
 */

#include "DadosSecao.h"

asn_TYPE_member_t asn_MBR_DadosSecao_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct DadosSecao, dataHoraAbertura),
		(ASN_TAG_CLASS_UNIVERSAL | (27 << 2)),
		0,
		&asn_DEF_ModuloBU_DataHoraJE,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"dataHoraAbertura"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct DadosSecao, dataHoraEncerramento),
		(ASN_TAG_CLASS_UNIVERSAL | (27 << 2)),
		0,
		&asn_DEF_ModuloBU_DataHoraJE,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"dataHoraEncerramento"
		},
	{ ATF_POINTER, 1, offsetof(struct DadosSecao, dataHoraDesligamentoVotoImpresso),
		(ASN_TAG_CLASS_UNIVERSAL | (27 << 2)),
		0,
		&asn_DEF_ModuloBU_DataHoraJE,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"dataHoraDesligamentoVotoImpresso"
		},
};
static const int asn_MAP_DadosSecao_oms_1[] = { 2 };
static const ber_tlv_tag_t asn_DEF_DadosSecao_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_DadosSecao_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (27 << 2)), 0, 0, 2 }, /* dataHoraAberturaat 224 */
    { (ASN_TAG_CLASS_UNIVERSAL | (27 << 2)), 1, -1, 1 }, /* dataHoraEncerramentoat 225 */
    { (ASN_TAG_CLASS_UNIVERSAL | (27 << 2)), 2, -2, 0 } /* dataHoraDesligamentoVotoImpressoat 226 */
};
asn_SEQUENCE_specifics_t asn_SPC_DadosSecao_specs_1 = {
	sizeof(struct DadosSecao),
	offsetof(struct DadosSecao, _asn_ctx),
	asn_MAP_DadosSecao_tag2el_1,
	3,	/* Count of tags in the map */
	asn_MAP_DadosSecao_oms_1,	/* Optional members */
	1, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_DadosSecao = {
	"DadosSecao",
	"DadosSecao",
	&asn_OP_SEQUENCE,
	asn_DEF_DadosSecao_tags_1,
	sizeof(asn_DEF_DadosSecao_tags_1)
		/sizeof(asn_DEF_DadosSecao_tags_1[0]), /* 1 */
	asn_DEF_DadosSecao_tags_1,	/* Same as above */
	sizeof(asn_DEF_DadosSecao_tags_1)
		/sizeof(asn_DEF_DadosSecao_tags_1[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_DadosSecao_1,
	3,	/* Elements count */
	&asn_SPC_DadosSecao_specs_1	/* Additional specs */
};

