/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ModuloBU"
 * 	found in "../../../asn/bu.asn1"
 * 	`asn1c -fline-refs -fcompound-names -fincludes-quoted`
 */

#ifndef	_DadosSecao_H_
#define	_DadosSecao_H_


#include "asn_application.h"

/* Including external dependencies */
#include "ModuloBU_DataHoraJE.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* DadosSecao */
typedef struct DadosSecao {
	ModuloBU_DataHoraJE_t	 dataHoraAbertura;
	ModuloBU_DataHoraJE_t	 dataHoraEncerramento;
	ModuloBU_DataHoraJE_t	*dataHoraDesligamentoVotoImpresso;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DadosSecao_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DadosSecao;
extern asn_SEQUENCE_specifics_t asn_SPC_DadosSecao_specs_1;
extern asn_TYPE_member_t asn_MBR_DadosSecao_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _DadosSecao_H_ */
#include "asn_internal.h"
