/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ModuloAssinaturaResultado"
 * 	found in "../../../asn/assinatura.asn1"
 * 	`asn1c -fline-refs -fcompound-names -fincludes-quoted`
 */

#ifndef	_DescritorChave_H_
#define	_DescritorChave_H_


#include "asn_application.h"

/* Including external dependencies */
#include "GeneralString.h"
#include "NativeInteger.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* DescritorChave */
typedef struct DescritorChave {
	GeneralString_t	 nomeUsuario;
	long	 serial;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DescritorChave_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DescritorChave;
extern asn_SEQUENCE_specifics_t asn_SPC_DescritorChave_specs_1;
extern asn_TYPE_member_t asn_MBR_DescritorChave_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _DescritorChave_H_ */
#include "asn_internal.h"
