/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ModuloRegistroDigitalVoto"
 * 	found in "../../../asn/rdv.asn1"
 * 	`asn1c -fline-refs -fcompound-names -fincludes-quoted`
 */

#ifndef	_Eleicoes_H_
#define	_Eleicoes_H_


#include "asn_application.h"

/* Including external dependencies */
#include "asn_SEQUENCE_OF.h"
#include "constr_SEQUENCE_OF.h"
#include "constr_CHOICE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Eleicoes_PR {
	Eleicoes_PR_NOTHING,	/* No components present */
	Eleicoes_PR_eleicoesVota,
	Eleicoes_PR_eleicoesSA
} Eleicoes_PR;

/* Forward declarations */
struct EleicaoVota;
struct EleicaoSA;

/* Eleicoes */
typedef struct Eleicoes {
	Eleicoes_PR present;
	union Eleicoes_u {
		struct Eleicoes__eleicoesVota {
			A_SEQUENCE_OF(struct EleicaoVota) list;
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} eleicoesVota;
		struct Eleicoes__eleicoesSA {
			A_SEQUENCE_OF(struct EleicaoSA) list;
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} eleicoesSA;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Eleicoes_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Eleicoes;
extern asn_CHOICE_specifics_t asn_SPC_Eleicoes_specs_1;
extern asn_TYPE_member_t asn_MBR_Eleicoes_1[2];
extern asn_per_constraints_t asn_PER_type_Eleicoes_constr_1;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "EleicaoVota.h"
#include "EleicaoSA.h"

#endif	/* _Eleicoes_H_ */
#include "asn_internal.h"
