/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ModuloRegistroDigitalVoto"
 * 	found in "../../../asn/rdv.asn1"
 * 	`asn1c -fline-refs -fcompound-names -fincludes-quoted`
 */

#ifndef	_EleicaoSA_H_
#define	_EleicaoSA_H_


#include "asn_application.h"

/* Including external dependencies */
#include "ModuloRegistroDigitalVoto_IDEleicao.h"
#include "TipoCedulaSA.h"
#include "OrigemVotosSA.h"
#include "asn_SEQUENCE_OF.h"
#include "constr_SEQUENCE_OF.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct VotosCargo;

/* EleicaoSA */
typedef struct EleicaoSA {
	ModuloRegistroDigitalVoto_IDEleicao_t	 idEleicao;
	TipoCedulaSA_t	 tipoCedulaSA;
	OrigemVotosSA_t	 origemVotosSA;
	struct EleicaoSA__votosCargos {
		A_SEQUENCE_OF(struct VotosCargo) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} votosCargos;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} EleicaoSA_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_EleicaoSA;
extern asn_SEQUENCE_specifics_t asn_SPC_EleicaoSA_specs_1;
extern asn_TYPE_member_t asn_MBR_EleicaoSA_1[4];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "VotosCargo.h"

#endif	/* _EleicaoSA_H_ */
#include "asn_internal.h"
