/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ModuloBU"
 * 	found in "../../../asn/bu.asn1"
 * 	`asn1c -fline-refs -fcompound-names -fincludes-quoted`
 */

#include "EntidadeEnvelopeGenerico.h"

static asn_TYPE_member_t asn_MBR_EntidadeEnvelopeGenerico_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct EntidadeEnvelopeGenerico, cabecalho),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_ModuloBU_CabecalhoEntidade,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"cabecalho"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct EntidadeEnvelopeGenerico, fase),
		(ASN_TAG_CLASS_UNIVERSAL | (10 << 2)),
		0,
		&asn_DEF_ModuloBU_Fase,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"fase"
		},
	{ ATF_POINTER, 1, offsetof(struct EntidadeEnvelopeGenerico, urna),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_ModuloBU_Urna,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"urna"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct EntidadeEnvelopeGenerico, identificacao),
		-1 /* Ambiguous tag (CHOICE?) */,
		0,
		&asn_DEF_ModuloBU_IdentificacaoUrna,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"identificacao"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct EntidadeEnvelopeGenerico, tipoEnvelope),
		(ASN_TAG_CLASS_UNIVERSAL | (10 << 2)),
		0,
		&asn_DEF_TipoEnvelope,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"tipoEnvelope"
		},
	{ ATF_POINTER, 1, offsetof(struct EntidadeEnvelopeGenerico, seguranca),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_Seguranca,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"seguranca"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct EntidadeEnvelopeGenerico, conteudo),
		(ASN_TAG_CLASS_UNIVERSAL | (4 << 2)),
		0,
		&asn_DEF_OCTET_STRING,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"conteudo"
		},
};
static const int asn_MAP_EntidadeEnvelopeGenerico_oms_1[] = { 2, 5 };
static const ber_tlv_tag_t asn_DEF_EntidadeEnvelopeGenerico_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_EntidadeEnvelopeGenerico_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (4 << 2)), 6, 0, 0 }, /* conteudoat 140 */
    { (ASN_TAG_CLASS_UNIVERSAL | (10 << 2)), 1, 0, 1 }, /* faseat 135 */
    { (ASN_TAG_CLASS_UNIVERSAL | (10 << 2)), 4, -1, 0 }, /* tipoEnvelopeat 138 */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 0, 0, 2 }, /* cabecalhoat 134 */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 2, -1, 1 }, /* urnaat 136 */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 5, -2, 0 }, /* segurancaat 139 */
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 3, 0, 0 }, /* identificacaoSecaoEleitoralat 270 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 3, 0, 0 } /* identificacaoContingenciaat 272 */
};
static asn_SEQUENCE_specifics_t asn_SPC_EntidadeEnvelopeGenerico_specs_1 = {
	sizeof(struct EntidadeEnvelopeGenerico),
	offsetof(struct EntidadeEnvelopeGenerico, _asn_ctx),
	asn_MAP_EntidadeEnvelopeGenerico_tag2el_1,
	8,	/* Count of tags in the map */
	asn_MAP_EntidadeEnvelopeGenerico_oms_1,	/* Optional members */
	2, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_EntidadeEnvelopeGenerico = {
	"EntidadeEnvelopeGenerico",
	"EntidadeEnvelopeGenerico",
	&asn_OP_SEQUENCE,
	asn_DEF_EntidadeEnvelopeGenerico_tags_1,
	sizeof(asn_DEF_EntidadeEnvelopeGenerico_tags_1)
		/sizeof(asn_DEF_EntidadeEnvelopeGenerico_tags_1[0]), /* 1 */
	asn_DEF_EntidadeEnvelopeGenerico_tags_1,	/* Same as above */
	sizeof(asn_DEF_EntidadeEnvelopeGenerico_tags_1)
		/sizeof(asn_DEF_EntidadeEnvelopeGenerico_tags_1[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_EntidadeEnvelopeGenerico_1,
	7,	/* Elements count */
	&asn_SPC_EntidadeEnvelopeGenerico_specs_1	/* Additional specs */
};

