/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ModuloBU"
 * 	found in "../../../asn/bu.asn1"
 * 	`asn1c -fline-refs -fcompound-names -fincludes-quoted`
 */

#ifndef	_EntidadeEnvelopeGenerico_H_
#define	_EntidadeEnvelopeGenerico_H_


#include "asn_application.h"

/* Including external dependencies */
#include "ModuloBU_CabecalhoEntidade.h"
#include "ModuloBU_Fase.h"
#include "ModuloBU_IdentificacaoUrna.h"
#include "TipoEnvelope.h"
#include "OCTET_STRING.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct Urna;
struct Seguranca;

/* EntidadeEnvelopeGenerico */
typedef struct EntidadeEnvelopeGenerico {
	ModuloBU_CabecalhoEntidade_t	 cabecalho;
	ModuloBU_Fase_t	 fase;
	struct Urna	*urna;	/* OPTIONAL */
	ModuloBU_IdentificacaoUrna_t	 identificacao;
	TipoEnvelope_t	 tipoEnvelope;
	struct Seguranca	*seguranca;	/* OPTIONAL */
	OCTET_STRING_t	 conteudo;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} EntidadeEnvelopeGenerico_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_EntidadeEnvelopeGenerico;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "ModuloBU_Urna.h"
#include "Seguranca.h"

#endif	/* _EntidadeEnvelopeGenerico_H_ */
#include "asn_internal.h"
