/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ModuloAssinaturaResultado"
 * 	found in "../../../asn/assinatura.asn1"
 * 	`asn1c -fline-refs -fcompound-names -fincludes-quoted`
 */

#ifndef	_EntidadeAssinaturaResultado_H_
#define	_EntidadeAssinaturaResultado_H_


#include "asn_application.h"

/* Including external dependencies */
#include "ModeloUrna.h"
#include "EntidadeAssinatura.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* EntidadeAssinaturaResultado */
typedef struct EntidadeAssinaturaResultado {
	ModeloUrna_t	 modeloUrna;
	EntidadeAssinatura_t	 assinaturaSW;
	EntidadeAssinatura_t	 assinaturaHW;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} EntidadeAssinaturaResultado_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_EntidadeAssinaturaResultado;

#ifdef __cplusplus
}
#endif

#endif	/* _EntidadeAssinaturaResultado_H_ */
#include "asn_internal.h"
