/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ModuloAssinaturaResultado"
 * 	found in "../../../asn/assinatura.asn1"
 * 	`asn1c -fline-refs -fcompound-names -fincludes-quoted`
 */

#ifndef	_EntidadeAssinatura_H_
#define	_EntidadeAssinatura_H_


#include "asn_application.h"

/* Including external dependencies */
#include "ModuloAssinaturaResultado_DataHoraJE.h"
#include "NativeInteger.h"
#include "AutoAssinaturaDigital.h"
#include "OCTET_STRING.h"
#include "GeneralString.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* EntidadeAssinatura */
typedef struct EntidadeAssinatura {
	ModuloAssinaturaResultado_DataHoraJE_t	 dataHoraCriacao;
	long	 versao;
	AutoAssinaturaDigital_t	 autoAssinado;
	OCTET_STRING_t	 conteudoAutoAssinado;
	OCTET_STRING_t	*certificadoDigital;	/* OPTIONAL */
	GeneralString_t	*conjuntoChave;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} EntidadeAssinatura_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_EntidadeAssinatura;
extern asn_SEQUENCE_specifics_t asn_SPC_EntidadeAssinatura_specs_1;
extern asn_TYPE_member_t asn_MBR_EntidadeAssinatura_1[6];

#ifdef __cplusplus
}
#endif

#endif	/* _EntidadeAssinatura_H_ */
#include "asn_internal.h"
