/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ModuloAssinaturaResultado"
 * 	found in "../../../asn/assinatura.asn1"
 * 	`asn1c -fline-refs -fcompound-names -fincludes-quoted`
 */

#include "EntidadeAssinaturaResultado.h"

static asn_TYPE_member_t asn_MBR_EntidadeAssinaturaResultado_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct EntidadeAssinaturaResultado, modeloUrna),
		(ASN_TAG_CLASS_UNIVERSAL | (10 << 2)),
		0,
		&asn_DEF_ModeloUrna,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"modeloUrna"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct EntidadeAssinaturaResultado, assinaturaSW),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_EntidadeAssinatura,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"assinaturaSW"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct EntidadeAssinaturaResultado, assinaturaHW),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_EntidadeAssinatura,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"assinaturaHW"
		},
};
static const ber_tlv_tag_t asn_DEF_EntidadeAssinaturaResultado_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_EntidadeAssinaturaResultado_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (10 << 2)), 0, 0, 0 }, /* modeloUrnaat 49 */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 1, 0, 1 }, /* assinaturaSWat 50 */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 2, -1, 0 } /* assinaturaHWat 52 */
};
static asn_SEQUENCE_specifics_t asn_SPC_EntidadeAssinaturaResultado_specs_1 = {
	sizeof(struct EntidadeAssinaturaResultado),
	offsetof(struct EntidadeAssinaturaResultado, _asn_ctx),
	asn_MAP_EntidadeAssinaturaResultado_tag2el_1,
	3,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_EntidadeAssinaturaResultado = {
	"EntidadeAssinaturaResultado",
	"EntidadeAssinaturaResultado",
	&asn_OP_SEQUENCE,
	asn_DEF_EntidadeAssinaturaResultado_tags_1,
	sizeof(asn_DEF_EntidadeAssinaturaResultado_tags_1)
		/sizeof(asn_DEF_EntidadeAssinaturaResultado_tags_1[0]), /* 1 */
	asn_DEF_EntidadeAssinaturaResultado_tags_1,	/* Same as above */
	sizeof(asn_DEF_EntidadeAssinaturaResultado_tags_1)
		/sizeof(asn_DEF_EntidadeAssinaturaResultado_tags_1[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_EntidadeAssinaturaResultado_1,
	3,	/* Elements count */
	&asn_SPC_EntidadeAssinaturaResultado_specs_1	/* Additional specs */
};

