/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ModuloRegistroDigitalVoto"
 * 	found in "../../../asn/rdv.asn1"
 * 	`asn1c -fline-refs -fcompound-names -fincludes-quoted`
 */

#include "EntidadeRegistroDigitalVoto.h"

asn_TYPE_member_t asn_MBR_EntidadeRegistroDigitalVoto_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct EntidadeRegistroDigitalVoto, pleito),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_ModuloRegistroDigitalVoto_IDPleito,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"pleito"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct EntidadeRegistroDigitalVoto, fase),
		(ASN_TAG_CLASS_UNIVERSAL | (10 << 2)),
		0,
		&asn_DEF_ModuloRegistroDigitalVoto_Fase,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"fase"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct EntidadeRegistroDigitalVoto, identificacao),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_ModuloRegistroDigitalVoto_IdentificacaoSecaoEleitoral,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"identificacao"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct EntidadeRegistroDigitalVoto, eleicoes),
		-1 /* Ambiguous tag (CHOICE?) */,
		0,
		&asn_DEF_Eleicoes,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"eleicoes"
		},
};
static const ber_tlv_tag_t asn_DEF_EntidadeRegistroDigitalVoto_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_EntidadeRegistroDigitalVoto_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 0, 0, 0 }, /* pleitoat 139 */
    { (ASN_TAG_CLASS_UNIVERSAL | (10 << 2)), 1, 0, 0 }, /* faseat 140 */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 2, 0, 0 }, /* identificacaoat 141 */
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 3, 0, 0 }, /* eleicoesVotaat 206 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 3, 0, 0 } /* eleicoesSAat 208 */
};
asn_SEQUENCE_specifics_t asn_SPC_EntidadeRegistroDigitalVoto_specs_1 = {
	sizeof(struct EntidadeRegistroDigitalVoto),
	offsetof(struct EntidadeRegistroDigitalVoto, _asn_ctx),
	asn_MAP_EntidadeRegistroDigitalVoto_tag2el_1,
	5,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_EntidadeRegistroDigitalVoto = {
	"EntidadeRegistroDigitalVoto",
	"EntidadeRegistroDigitalVoto",
	&asn_OP_SEQUENCE,
	asn_DEF_EntidadeRegistroDigitalVoto_tags_1,
	sizeof(asn_DEF_EntidadeRegistroDigitalVoto_tags_1)
		/sizeof(asn_DEF_EntidadeRegistroDigitalVoto_tags_1[0]), /* 1 */
	asn_DEF_EntidadeRegistroDigitalVoto_tags_1,	/* Same as above */
	sizeof(asn_DEF_EntidadeRegistroDigitalVoto_tags_1)
		/sizeof(asn_DEF_EntidadeRegistroDigitalVoto_tags_1[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_EntidadeRegistroDigitalVoto_1,
	4,	/* Elements count */
	&asn_SPC_EntidadeRegistroDigitalVoto_specs_1	/* Additional specs */
};

