/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ModuloRegistroDigitalVoto"
 * 	found in "../../../asn/rdv.asn1"
 * 	`asn1c -fline-refs -fcompound-names -fincludes-quoted`
 */

#ifndef	_EntidadeResultadoRDV_H_
#define	_EntidadeResultadoRDV_H_


#include "asn_application.h"

/* Including external dependencies */
#include "ModuloRegistroDigitalVoto_CabecalhoEntidade.h"
#include "ModuloRegistroDigitalVoto_Urna.h"
#include "EntidadeRegistroDigitalVoto.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* EntidadeResultadoRDV */
typedef struct EntidadeResultadoRDV {
	ModuloRegistroDigitalVoto_CabecalhoEntidade_t	 cabecalho;
	ModuloRegistroDigitalVoto_Urna_t	 urna;
	EntidadeRegistroDigitalVoto_t	 rdv;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} EntidadeResultadoRDV_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_EntidadeResultadoRDV;

#ifdef __cplusplus
}
#endif

#endif	/* _EntidadeResultadoRDV_H_ */
#include "asn_internal.h"
