/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ModuloBU"
 * 	found in "../../../asn/bu.asn1"
 * 	`asn1c -fline-refs -fcompound-names -fincludes-quoted`
 */

#ifndef	_HistoricoVotoImpresso_H_
#define	_HistoricoVotoImpresso_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"
#include "ModuloBU_DataHoraJE.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* HistoricoVotoImpresso */
typedef struct HistoricoVotoImpresso {
	long	 idImpressoraVotos;
	long	 idRepositorioVotos;
	ModuloBU_DataHoraJE_t	 dataHoraLigamento;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} HistoricoVotoImpresso_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_HistoricoVotoImpresso;
extern asn_SEQUENCE_specifics_t asn_SPC_HistoricoVotoImpresso_specs_1;
extern asn_TYPE_member_t asn_MBR_HistoricoVotoImpresso_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _HistoricoVotoImpresso_H_ */
#include "asn_internal.h"
