/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ModuloBU"
 * 	found in "../../../asn/bu.asn1"
 * 	`asn1c -fline-refs -fcompound-names -fincludes-quoted`
 */

#ifndef	_IdentificacaoMesaJustificativa_H_
#define	_IdentificacaoMesaJustificativa_H_


#include "asn_application.h"

/* Including external dependencies */
#include "ModuloBU_MunicipioZona.h"
#include "NumeroMesa.h"
#include "NumeroUrna.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* IdentificacaoMesaJustificativa */
typedef struct IdentificacaoMesaJustificativa {
	ModuloBU_MunicipioZona_t	 municipioZona;
	NumeroMesa_t	 mesa;
	NumeroUrna_t	 urna;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} IdentificacaoMesaJustificativa_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_IdentificacaoMesaJustificativa;

#ifdef __cplusplus
}
#endif

#endif	/* _IdentificacaoMesaJustificativa_H_ */
#include "asn_internal.h"
