/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ModuloAssinaturaResultado"
 * 	found in "../../../asn/assinatura.asn1"
 * 	`asn1c -fline-refs -fcompound-names -fincludes-quoted`
 */

#ifndef	_ModeloUrna_H_
#define	_ModeloUrna_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeEnumerated.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ModeloUrna {
	ModeloUrna_ue2009	= 9,
	ModeloUrna_ue2010	= 10,
	ModeloUrna_ue2011	= 11,
	ModeloUrna_ue2013	= 13,
	ModeloUrna_ue2015	= 15,
	ModeloUrna_ue2020	= 20
} e_ModeloUrna;

/* ModeloUrna */
typedef long	 ModeloUrna_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_ModeloUrna_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_ModeloUrna;
extern const asn_INTEGER_specifics_t asn_SPC_ModeloUrna_specs_1;
asn_struct_free_f ModeloUrna_free;
asn_struct_print_f ModeloUrna_print;
asn_constr_check_f ModeloUrna_constraint;
ber_type_decoder_f ModeloUrna_decode_ber;
der_type_encoder_f ModeloUrna_encode_der;
xer_type_decoder_f ModeloUrna_decode_xer;
xer_type_encoder_f ModeloUrna_encode_xer;
jer_type_encoder_f ModeloUrna_encode_jer;
oer_type_decoder_f ModeloUrna_decode_oer;
oer_type_encoder_f ModeloUrna_encode_oer;
per_type_decoder_f ModeloUrna_decode_uper;
per_type_encoder_f ModeloUrna_encode_uper;
per_type_decoder_f ModeloUrna_decode_aper;
per_type_encoder_f ModeloUrna_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _ModeloUrna_H_ */
#include "asn_internal.h"
