/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ModuloAssinaturaResultado"
 * 	found in "../../../asn/assinatura.asn1"
 * 	`asn1c -fline-refs -fcompound-names -fincludes-quoted`
 */

#include "ModeloUrna.h"

/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
#if !defined(ASN_DISABLE_OER_SUPPORT)
static asn_oer_constraints_t asn_OER_type_ModeloUrna_constr_1 CC_NOTUSED = {
	{ 0, 0 },
	-1};
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
asn_per_constraints_t asn_PER_type_ModeloUrna_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 3,  3,  0,  5 }	/* (0..5) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
static const asn_INTEGER_enum_map_t asn_MAP_ModeloUrna_value2enum_1[] = {
	{ 9,	6,	"ue2009" },
	{ 10,	6,	"ue2010" },
	{ 11,	6,	"ue2011" },
	{ 13,	6,	"ue2013" },
	{ 15,	6,	"ue2015" },
	{ 20,	6,	"ue2020" }
};
static const unsigned int asn_MAP_ModeloUrna_enum2value_1[] = {
	0,	/* ue2009(9) */
	1,	/* ue2010(10) */
	2,	/* ue2011(11) */
	3,	/* ue2013(13) */
	4,	/* ue2015(15) */
	5	/* ue2020(20) */
};
const asn_INTEGER_specifics_t asn_SPC_ModeloUrna_specs_1 = {
	asn_MAP_ModeloUrna_value2enum_1,	/* "tag" => N; sorted by tag */
	asn_MAP_ModeloUrna_enum2value_1,	/* N => "tag"; sorted by N */
	6,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_ModeloUrna_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
asn_TYPE_descriptor_t asn_DEF_ModeloUrna = {
	"ModeloUrna",
	"ModeloUrna",
	&asn_OP_NativeEnumerated,
	asn_DEF_ModeloUrna_tags_1,
	sizeof(asn_DEF_ModeloUrna_tags_1)
		/sizeof(asn_DEF_ModeloUrna_tags_1[0]), /* 1 */
	asn_DEF_ModeloUrna_tags_1,	/* Same as above */
	sizeof(asn_DEF_ModeloUrna_tags_1)
		/sizeof(asn_DEF_ModeloUrna_tags_1[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		&asn_OER_type_ModeloUrna_constr_1,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_ModeloUrna_constr_1,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		NativeEnumerated_constraint
	},
	0, 0,	/* Defined elsewhere */
	&asn_SPC_ModeloUrna_specs_1	/* Additional specs */
};

