/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ModuloBU"
 * 	found in "../../../asn/bu.asn1"
 * 	`asn1c -fline-refs -fcompound-names -fincludes-quoted`
 */

#ifndef	_ModuloBU_TipoApuracao_H_
#define	_ModuloBU_TipoApuracao_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeEnumerated.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ModuloBU_TipoApuracao {
	ModuloBU_TipoApuracao_totalmenteManual	= 1,
	ModuloBU_TipoApuracao_totalmenteEletronica	= 2,
	ModuloBU_TipoApuracao_mistaBU	= 3,
	ModuloBU_TipoApuracao_mistaMR	= 4
} e_ModuloBU_TipoApuracao;

/* ModuloBU_TipoApuracao */
typedef long	 ModuloBU_TipoApuracao_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_ModuloBU_TipoApuracao_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_ModuloBU_TipoApuracao;
extern const asn_INTEGER_specifics_t asn_SPC_ModuloBU_TipoApuracao_specs_1;
asn_struct_free_f ModuloBU_TipoApuracao_free;
asn_struct_print_f ModuloBU_TipoApuracao_print;
asn_constr_check_f ModuloBU_TipoApuracao_constraint;
ber_type_decoder_f ModuloBU_TipoApuracao_decode_ber;
der_type_encoder_f ModuloBU_TipoApuracao_encode_der;
xer_type_decoder_f ModuloBU_TipoApuracao_decode_xer;
xer_type_encoder_f ModuloBU_TipoApuracao_encode_xer;
jer_type_encoder_f ModuloBU_TipoApuracao_encode_jer;
oer_type_decoder_f ModuloBU_TipoApuracao_decode_oer;
oer_type_encoder_f ModuloBU_TipoApuracao_encode_oer;
per_type_decoder_f ModuloBU_TipoApuracao_decode_uper;
per_type_encoder_f ModuloBU_TipoApuracao_encode_uper;
per_type_decoder_f ModuloBU_TipoApuracao_decode_aper;
per_type_encoder_f ModuloBU_TipoApuracao_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _ModuloBU_TipoApuracao_H_ */
#include "asn_internal.h"
