/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ModuloRegistroDigitalVoto"
 * 	found in "../../../asn/rdv.asn1"
 * 	`asn1c -fline-refs -fcompound-names -fincludes-quoted`
 */

#ifndef	_ModuloRegistroDigitalVoto_TipoApuracaoSA_H_
#define	_ModuloRegistroDigitalVoto_TipoApuracaoSA_H_


#include "asn_application.h"

/* Including external dependencies */
#include "ModuloRegistroDigitalVoto_ApuracaoMistaMR.h"
#include "ModuloRegistroDigitalVoto_ApuracaoMistaBUAE.h"
#include "ModuloRegistroDigitalVoto_ApuracaoTotalmenteManualDigitacaoAE.h"
#include "ModuloRegistroDigitalVoto_ApuracaoEletronica.h"
#include "constr_CHOICE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ModuloRegistroDigitalVoto_TipoApuracaoSA_PR {
	ModuloRegistroDigitalVoto_TipoApuracaoSA_PR_NOTHING,	/* No components present */
	ModuloRegistroDigitalVoto_TipoApuracaoSA_PR_apuracaoMistaMR,
	ModuloRegistroDigitalVoto_TipoApuracaoSA_PR_apuracaoMistaBUAE,
	ModuloRegistroDigitalVoto_TipoApuracaoSA_PR_apuracaoTotalmenteManual,
	ModuloRegistroDigitalVoto_TipoApuracaoSA_PR_apuracaoEletronica
} ModuloRegistroDigitalVoto_TipoApuracaoSA_PR;

/* ModuloRegistroDigitalVoto_TipoApuracaoSA */
typedef struct ModuloRegistroDigitalVoto_TipoApuracaoSA {
	ModuloRegistroDigitalVoto_TipoApuracaoSA_PR present;
	union ModuloRegistroDigitalVoto_TipoApuracaoSA_u {
		ModuloRegistroDigitalVoto_ApuracaoMistaMR_t	 apuracaoMistaMR;
		ModuloRegistroDigitalVoto_ApuracaoMistaBUAE_t	 apuracaoMistaBUAE;
		ModuloRegistroDigitalVoto_ApuracaoTotalmenteManualDigitacaoAE_t	 apuracaoTotalmenteManual;
		ModuloRegistroDigitalVoto_ApuracaoEletronica_t	 apuracaoEletronica;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ModuloRegistroDigitalVoto_TipoApuracaoSA_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ModuloRegistroDigitalVoto_TipoApuracaoSA;
extern asn_CHOICE_specifics_t asn_SPC_ModuloRegistroDigitalVoto_TipoApuracaoSA_specs_1;
extern asn_TYPE_member_t asn_MBR_ModuloRegistroDigitalVoto_TipoApuracaoSA_1[4];
extern asn_per_constraints_t asn_PER_type_ModuloRegistroDigitalVoto_TipoApuracaoSA_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _ModuloRegistroDigitalVoto_TipoApuracaoSA_H_ */
#include "asn_internal.h"
