/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ModuloRegistroDigitalVoto"
 * 	found in "../../../asn/rdv.asn1"
 * 	`asn1c -fline-refs -fcompound-names -fincludes-quoted`
 */

#ifndef	_ModuloRegistroDigitalVoto_IdentificacaoUrna_H_
#define	_ModuloRegistroDigitalVoto_IdentificacaoUrna_H_


#include "asn_application.h"

/* Including external dependencies */
#include "ModuloRegistroDigitalVoto_IdentificacaoSecaoEleitoral.h"
#include "ModuloRegistroDigitalVoto_IdentificacaoContingencia.h"
#include "constr_CHOICE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ModuloRegistroDigitalVoto_IdentificacaoUrna_PR {
	ModuloRegistroDigitalVoto_IdentificacaoUrna_PR_NOTHING,	/* No components present */
	ModuloRegistroDigitalVoto_IdentificacaoUrna_PR_identificacaoSecaoEleitoral,
	ModuloRegistroDigitalVoto_IdentificacaoUrna_PR_identificacaoContingencia
} ModuloRegistroDigitalVoto_IdentificacaoUrna_PR;

/* ModuloRegistroDigitalVoto_IdentificacaoUrna */
typedef struct ModuloRegistroDigitalVoto_IdentificacaoUrna {
	ModuloRegistroDigitalVoto_IdentificacaoUrna_PR present;
	union ModuloRegistroDigitalVoto_IdentificacaoUrna_u {
		ModuloRegistroDigitalVoto_IdentificacaoSecaoEleitoral_t	 identificacaoSecaoEleitoral;
		ModuloRegistroDigitalVoto_IdentificacaoContingencia_t	 identificacaoContingencia;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ModuloRegistroDigitalVoto_IdentificacaoUrna_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ModuloRegistroDigitalVoto_IdentificacaoUrna;
extern asn_CHOICE_specifics_t asn_SPC_ModuloRegistroDigitalVoto_IdentificacaoUrna_specs_1;
extern asn_TYPE_member_t asn_MBR_ModuloRegistroDigitalVoto_IdentificacaoUrna_1[2];
extern asn_per_constraints_t asn_PER_type_ModuloRegistroDigitalVoto_IdentificacaoUrna_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _ModuloRegistroDigitalVoto_IdentificacaoUrna_H_ */
#include "asn_internal.h"
