/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ModuloBU"
 * 	found in "../../../asn/bu.asn1"
 * 	`asn1c -fline-refs -fcompound-names -fincludes-quoted`
 */

#ifndef	_ModuloBU_TipoApuracaoSA_H_
#define	_ModuloBU_TipoApuracaoSA_H_


#include "asn_application.h"

/* Including external dependencies */
#include "ModuloBU_ApuracaoMistaMR.h"
#include "ModuloBU_ApuracaoMistaBUAE.h"
#include "ModuloBU_ApuracaoTotalmenteManualDigitacaoAE.h"
#include "ModuloBU_ApuracaoEletronica.h"
#include "constr_CHOICE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ModuloBU_TipoApuracaoSA_PR {
	ModuloBU_TipoApuracaoSA_PR_NOTHING,	/* No components present */
	ModuloBU_TipoApuracaoSA_PR_apuracaoMistaMR,
	ModuloBU_TipoApuracaoSA_PR_apuracaoMistaBUAE,
	ModuloBU_TipoApuracaoSA_PR_apuracaoTotalmenteManual,
	ModuloBU_TipoApuracaoSA_PR_apuracaoEletronica
} ModuloBU_TipoApuracaoSA_PR;

/* ModuloBU_TipoApuracaoSA */
typedef struct ModuloBU_TipoApuracaoSA {
	ModuloBU_TipoApuracaoSA_PR present;
	union ModuloBU_TipoApuracaoSA_u {
		ModuloBU_ApuracaoMistaMR_t	 apuracaoMistaMR;
		ModuloBU_ApuracaoMistaBUAE_t	 apuracaoMistaBUAE;
		ModuloBU_ApuracaoTotalmenteManualDigitacaoAE_t	 apuracaoTotalmenteManual;
		ModuloBU_ApuracaoEletronica_t	 apuracaoEletronica;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ModuloBU_TipoApuracaoSA_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ModuloBU_TipoApuracaoSA;
extern asn_CHOICE_specifics_t asn_SPC_ModuloBU_TipoApuracaoSA_specs_1;
extern asn_TYPE_member_t asn_MBR_ModuloBU_TipoApuracaoSA_1[4];
extern asn_per_constraints_t asn_PER_type_ModuloBU_TipoApuracaoSA_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _ModuloBU_TipoApuracaoSA_H_ */
#include "asn_internal.h"
