/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ModuloBU"
 * 	found in "../../../asn/bu.asn1"
 * 	`asn1c -fline-refs -fcompound-names -fincludes-quoted`
 */

#include "ModuloBU_CargoConstitucional.h"

/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
#if !defined(ASN_DISABLE_OER_SUPPORT)
static asn_oer_constraints_t asn_OER_type_ModuloBU_CargoConstitucional_constr_1 CC_NOTUSED = {
	{ 0, 0 },
	-1};
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
asn_per_constraints_t asn_PER_type_ModuloBU_CargoConstitucional_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 4,  4,  0,  12 }	/* (0..12) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
static const asn_INTEGER_enum_map_t asn_MAP_ModuloBU_CargoConstitucional_value2enum_1[] = {
	{ 1,	10,	"presidente" },
	{ 2,	14,	"vicePresidente" },
	{ 3,	10,	"governador" },
	{ 4,	14,	"viceGovernador" },
	{ 5,	7,	"senador" },
	{ 6,	15,	"deputadoFederal" },
	{ 7,	16,	"deputadoEstadual" },
	{ 8,	17,	"deputadoDistrital" },
	{ 9,	23,	"primeiroSuplenteSenador" },
	{ 10,	22,	"segundoSuplenteSenador" },
	{ 11,	8,	"prefeito" },
	{ 12,	12,	"vicePrefeito" },
	{ 13,	8,	"vereador" }
};
static const unsigned int asn_MAP_ModuloBU_CargoConstitucional_enum2value_1[] = {
	7,	/* deputadoDistrital(8) */
	6,	/* deputadoEstadual(7) */
	5,	/* deputadoFederal(6) */
	2,	/* governador(3) */
	10,	/* prefeito(11) */
	0,	/* presidente(1) */
	8,	/* primeiroSuplenteSenador(9) */
	9,	/* segundoSuplenteSenador(10) */
	4,	/* senador(5) */
	12,	/* vereador(13) */
	3,	/* viceGovernador(4) */
	11,	/* vicePrefeito(12) */
	1	/* vicePresidente(2) */
};
const asn_INTEGER_specifics_t asn_SPC_ModuloBU_CargoConstitucional_specs_1 = {
	asn_MAP_ModuloBU_CargoConstitucional_value2enum_1,	/* "tag" => N; sorted by tag */
	asn_MAP_ModuloBU_CargoConstitucional_enum2value_1,	/* N => "tag"; sorted by N */
	13,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_ModuloBU_CargoConstitucional_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
asn_TYPE_descriptor_t asn_DEF_ModuloBU_CargoConstitucional = {
	"CargoConstitucional",
	"CargoConstitucional",
	&asn_OP_NativeEnumerated,
	asn_DEF_ModuloBU_CargoConstitucional_tags_1,
	sizeof(asn_DEF_ModuloBU_CargoConstitucional_tags_1)
		/sizeof(asn_DEF_ModuloBU_CargoConstitucional_tags_1[0]), /* 1 */
	asn_DEF_ModuloBU_CargoConstitucional_tags_1,	/* Same as above */
	sizeof(asn_DEF_ModuloBU_CargoConstitucional_tags_1)
		/sizeof(asn_DEF_ModuloBU_CargoConstitucional_tags_1[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		&asn_OER_type_ModuloBU_CargoConstitucional_constr_1,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_ModuloBU_CargoConstitucional_constr_1,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		NativeEnumerated_constraint
	},
	0, 0,	/* Defined elsewhere */
	&asn_SPC_ModuloBU_CargoConstitucional_specs_1	/* Additional specs */
};

