/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ModuloBU"
 * 	found in "../../../asn/bu.asn1"
 * 	`asn1c -fline-refs -fcompound-names -fincludes-quoted`
 */

#ifndef	_ModuloBU_Fase_H_
#define	_ModuloBU_Fase_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeEnumerated.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ModuloBU_Fase {
	ModuloBU_Fase_simulado	= 1,
	ModuloBU_Fase_oficial	= 2,
	ModuloBU_Fase_treinamento	= 3
} e_ModuloBU_Fase;

/* ModuloBU_Fase */
typedef long	 ModuloBU_Fase_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_ModuloBU_Fase_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_ModuloBU_Fase;
extern const asn_INTEGER_specifics_t asn_SPC_ModuloBU_Fase_specs_1;
asn_struct_free_f ModuloBU_Fase_free;
asn_struct_print_f ModuloBU_Fase_print;
asn_constr_check_f ModuloBU_Fase_constraint;
ber_type_decoder_f ModuloBU_Fase_decode_ber;
der_type_encoder_f ModuloBU_Fase_encode_der;
xer_type_decoder_f ModuloBU_Fase_decode_xer;
xer_type_encoder_f ModuloBU_Fase_encode_xer;
jer_type_encoder_f ModuloBU_Fase_encode_jer;
oer_type_decoder_f ModuloBU_Fase_decode_oer;
oer_type_encoder_f ModuloBU_Fase_encode_oer;
per_type_decoder_f ModuloBU_Fase_decode_uper;
per_type_encoder_f ModuloBU_Fase_encode_uper;
per_type_decoder_f ModuloBU_Fase_decode_aper;
per_type_encoder_f ModuloBU_Fase_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _ModuloBU_Fase_H_ */
#include "asn_internal.h"
