/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ModuloBU"
 * 	found in "../../../asn/bu.asn1"
 * 	`asn1c -fline-refs -fcompound-names -fincludes-quoted`
 */

#ifndef	_ModuloBU_MunicipioZona_H_
#define	_ModuloBU_MunicipioZona_H_


#include "asn_application.h"

/* Including external dependencies */
#include "ModuloBU_CodigoMunicipio.h"
#include "ModuloBU_NumeroZona.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* ModuloBU_MunicipioZona */
typedef struct ModuloBU_MunicipioZona {
	ModuloBU_CodigoMunicipio_t	 municipio;
	ModuloBU_NumeroZona_t	 zona;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ModuloBU_MunicipioZona_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ModuloBU_MunicipioZona;
extern asn_SEQUENCE_specifics_t asn_SPC_ModuloBU_MunicipioZona_specs_1;
extern asn_TYPE_member_t asn_MBR_ModuloBU_MunicipioZona_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _ModuloBU_MunicipioZona_H_ */
#include "asn_internal.h"
