/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ModuloRegistroDigitalVoto"
 * 	found in "../../../asn/rdv.asn1"
 * 	`asn1c -fline-refs -fcompound-names -fincludes-quoted`
 */

#ifndef	_ModuloRegistroDigitalVoto_ApuracaoMistaBUAE_H_
#define	_ModuloRegistroDigitalVoto_ApuracaoMistaBUAE_H_


#include "asn_application.h"

/* Including external dependencies */
#include "ModuloRegistroDigitalVoto_TipoApuracao.h"
#include "ModuloRegistroDigitalVoto_MotivoApuracaoMistaComBU.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* ModuloRegistroDigitalVoto_ApuracaoMistaBUAE */
typedef struct ModuloRegistroDigitalVoto_ApuracaoMistaBUAE {
	ModuloRegistroDigitalVoto_TipoApuracao_t	 tipoapuracao;
	ModuloRegistroDigitalVoto_MotivoApuracaoMistaComBU_t	 motivoApuracao;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ModuloRegistroDigitalVoto_ApuracaoMistaBUAE_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ModuloRegistroDigitalVoto_ApuracaoMistaBUAE;
extern asn_SEQUENCE_specifics_t asn_SPC_ModuloRegistroDigitalVoto_ApuracaoMistaBUAE_specs_1;
extern asn_TYPE_member_t asn_MBR_ModuloRegistroDigitalVoto_ApuracaoMistaBUAE_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _ModuloRegistroDigitalVoto_ApuracaoMistaBUAE_H_ */
#include "asn_internal.h"
