/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ModuloRegistroDigitalVoto"
 * 	found in "../../../asn/rdv.asn1"
 * 	`asn1c -fline-refs -fcompound-names -fincludes-quoted`
 */

#ifndef	_ModuloRegistroDigitalVoto_IDProcessoEleitoral_H_
#define	_ModuloRegistroDigitalVoto_IDProcessoEleitoral_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"

#ifdef __cplusplus
extern "C" {
#endif

/* ModuloRegistroDigitalVoto_IDProcessoEleitoral */
typedef long	 ModuloRegistroDigitalVoto_IDProcessoEleitoral_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_ModuloRegistroDigitalVoto_IDProcessoEleitoral_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_ModuloRegistroDigitalVoto_IDProcessoEleitoral;
asn_struct_free_f ModuloRegistroDigitalVoto_IDProcessoEleitoral_free;
asn_struct_print_f ModuloRegistroDigitalVoto_IDProcessoEleitoral_print;
asn_constr_check_f ModuloRegistroDigitalVoto_IDProcessoEleitoral_constraint;
ber_type_decoder_f ModuloRegistroDigitalVoto_IDProcessoEleitoral_decode_ber;
der_type_encoder_f ModuloRegistroDigitalVoto_IDProcessoEleitoral_encode_der;
xer_type_decoder_f ModuloRegistroDigitalVoto_IDProcessoEleitoral_decode_xer;
xer_type_encoder_f ModuloRegistroDigitalVoto_IDProcessoEleitoral_encode_xer;
jer_type_encoder_f ModuloRegistroDigitalVoto_IDProcessoEleitoral_encode_jer;
oer_type_decoder_f ModuloRegistroDigitalVoto_IDProcessoEleitoral_decode_oer;
oer_type_encoder_f ModuloRegistroDigitalVoto_IDProcessoEleitoral_encode_oer;
per_type_decoder_f ModuloRegistroDigitalVoto_IDProcessoEleitoral_decode_uper;
per_type_encoder_f ModuloRegistroDigitalVoto_IDProcessoEleitoral_encode_uper;
per_type_decoder_f ModuloRegistroDigitalVoto_IDProcessoEleitoral_decode_aper;
per_type_encoder_f ModuloRegistroDigitalVoto_IDProcessoEleitoral_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _ModuloRegistroDigitalVoto_IDProcessoEleitoral_H_ */
#include "asn_internal.h"
