/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ModuloRegistroDigitalVoto"
 * 	found in "../../../asn/rdv.asn1"
 * 	`asn1c -fline-refs -fcompound-names -fincludes-quoted`
 */

#ifndef	_ModuloRegistroDigitalVoto_CorrespondenciaResultado_H_
#define	_ModuloRegistroDigitalVoto_CorrespondenciaResultado_H_


#include "asn_application.h"

/* Including external dependencies */
#include "ModuloRegistroDigitalVoto_IdentificacaoUrna.h"
#include "ModuloRegistroDigitalVoto_Carga.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* ModuloRegistroDigitalVoto_CorrespondenciaResultado */
typedef struct ModuloRegistroDigitalVoto_CorrespondenciaResultado {
	ModuloRegistroDigitalVoto_IdentificacaoUrna_t	 identificacao;
	ModuloRegistroDigitalVoto_Carga_t	 carga;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ModuloRegistroDigitalVoto_CorrespondenciaResultado_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ModuloRegistroDigitalVoto_CorrespondenciaResultado;
extern asn_SEQUENCE_specifics_t asn_SPC_ModuloRegistroDigitalVoto_CorrespondenciaResultado_specs_1;
extern asn_TYPE_member_t asn_MBR_ModuloRegistroDigitalVoto_CorrespondenciaResultado_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _ModuloRegistroDigitalVoto_CorrespondenciaResultado_H_ */
#include "asn_internal.h"
