/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ModuloRegistroDigitalVoto"
 * 	found in "../../../asn/rdv.asn1"
 * 	`asn1c -fline-refs -fcompound-names -fincludes-quoted`
 */

#include "ModuloRegistroDigitalVoto_TipoArquivo.h"

/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
#if !defined(ASN_DISABLE_OER_SUPPORT)
static asn_oer_constraints_t asn_OER_type_ModuloRegistroDigitalVoto_TipoArquivo_constr_1 CC_NOTUSED = {
	{ 0, 0 },
	-1};
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
asn_per_constraints_t asn_PER_type_ModuloRegistroDigitalVoto_TipoArquivo_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 3,  3,  0,  5 }	/* (0..5) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
static const asn_INTEGER_enum_map_t asn_MAP_ModuloRegistroDigitalVoto_TipoArquivo_value2enum_1[] = {
	{ 1,	9,	"votacaoUE" },
	{ 2,	10,	"votacaoRED" },
	{ 3,	22,	"saMistaMRParcialCedula" },
	{ 4,	23,	"saMistaBUImpressoCedula" },
	{ 5,	8,	"saManual" },
	{ 6,	12,	"saEletronica" }
};
static const unsigned int asn_MAP_ModuloRegistroDigitalVoto_TipoArquivo_enum2value_1[] = {
	5,	/* saEletronica(6) */
	4,	/* saManual(5) */
	3,	/* saMistaBUImpressoCedula(4) */
	2,	/* saMistaMRParcialCedula(3) */
	1,	/* votacaoRED(2) */
	0	/* votacaoUE(1) */
};
const asn_INTEGER_specifics_t asn_SPC_ModuloRegistroDigitalVoto_TipoArquivo_specs_1 = {
	asn_MAP_ModuloRegistroDigitalVoto_TipoArquivo_value2enum_1,	/* "tag" => N; sorted by tag */
	asn_MAP_ModuloRegistroDigitalVoto_TipoArquivo_enum2value_1,	/* N => "tag"; sorted by N */
	6,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_ModuloRegistroDigitalVoto_TipoArquivo_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
asn_TYPE_descriptor_t asn_DEF_ModuloRegistroDigitalVoto_TipoArquivo = {
	"TipoArquivo",
	"TipoArquivo",
	&asn_OP_NativeEnumerated,
	asn_DEF_ModuloRegistroDigitalVoto_TipoArquivo_tags_1,
	sizeof(asn_DEF_ModuloRegistroDigitalVoto_TipoArquivo_tags_1)
		/sizeof(asn_DEF_ModuloRegistroDigitalVoto_TipoArquivo_tags_1[0]), /* 1 */
	asn_DEF_ModuloRegistroDigitalVoto_TipoArquivo_tags_1,	/* Same as above */
	sizeof(asn_DEF_ModuloRegistroDigitalVoto_TipoArquivo_tags_1)
		/sizeof(asn_DEF_ModuloRegistroDigitalVoto_TipoArquivo_tags_1[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		&asn_OER_type_ModuloRegistroDigitalVoto_TipoArquivo_constr_1,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_ModuloRegistroDigitalVoto_TipoArquivo_constr_1,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		NativeEnumerated_constraint
	},
	0, 0,	/* Defined elsewhere */
	&asn_SPC_ModuloRegistroDigitalVoto_TipoArquivo_specs_1	/* Additional specs */
};

