/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ModuloRegistroDigitalVoto"
 * 	found in "../../../asn/rdv.asn1"
 * 	`asn1c -fline-refs -fcompound-names -fincludes-quoted`
 */

#include "ModuloRegistroDigitalVoto_CabecalhoEntidade.h"

asn_TYPE_member_t asn_MBR_ModuloRegistroDigitalVoto_CabecalhoEntidade_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ModuloRegistroDigitalVoto_CabecalhoEntidade, dataGeracao),
		(ASN_TAG_CLASS_UNIVERSAL | (27 << 2)),
		0,
		&asn_DEF_ModuloRegistroDigitalVoto_DataHoraJE,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"dataGeracao"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ModuloRegistroDigitalVoto_CabecalhoEntidade, idEleitoral),
		-1 /* Ambiguous tag (CHOICE?) */,
		0,
		&asn_DEF_ModuloRegistroDigitalVoto_IDEleitoral,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"idEleitoral"
		},
};
static const ber_tlv_tag_t asn_DEF_ModuloRegistroDigitalVoto_CabecalhoEntidade_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_ModuloRegistroDigitalVoto_CabecalhoEntidade_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (27 << 2)), 0, 0, 0 }, /* dataGeracaoat 167 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* idProcessoEleitoralat 212 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 1, 0, 0 }, /* idPleitoat 213 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 1, 0, 0 } /* idEleicaoat 215 */
};
asn_SEQUENCE_specifics_t asn_SPC_ModuloRegistroDigitalVoto_CabecalhoEntidade_specs_1 = {
	sizeof(struct ModuloRegistroDigitalVoto_CabecalhoEntidade),
	offsetof(struct ModuloRegistroDigitalVoto_CabecalhoEntidade, _asn_ctx),
	asn_MAP_ModuloRegistroDigitalVoto_CabecalhoEntidade_tag2el_1,
	4,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_ModuloRegistroDigitalVoto_CabecalhoEntidade = {
	"CabecalhoEntidade",
	"CabecalhoEntidade",
	&asn_OP_SEQUENCE,
	asn_DEF_ModuloRegistroDigitalVoto_CabecalhoEntidade_tags_1,
	sizeof(asn_DEF_ModuloRegistroDigitalVoto_CabecalhoEntidade_tags_1)
		/sizeof(asn_DEF_ModuloRegistroDigitalVoto_CabecalhoEntidade_tags_1[0]), /* 1 */
	asn_DEF_ModuloRegistroDigitalVoto_CabecalhoEntidade_tags_1,	/* Same as above */
	sizeof(asn_DEF_ModuloRegistroDigitalVoto_CabecalhoEntidade_tags_1)
		/sizeof(asn_DEF_ModuloRegistroDigitalVoto_CabecalhoEntidade_tags_1[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_ModuloRegistroDigitalVoto_CabecalhoEntidade_1,
	2,	/* Elements count */
	&asn_SPC_ModuloRegistroDigitalVoto_CabecalhoEntidade_specs_1	/* Additional specs */
};

