/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ModuloRegistroDigitalVoto"
 * 	found in "../../../asn/rdv.asn1"
 * 	`asn1c -fline-refs -fcompound-names -fincludes-quoted`
 */

#ifndef	_ModuloRegistroDigitalVoto_DataHoraJE_H_
#define	_ModuloRegistroDigitalVoto_DataHoraJE_H_


#include "asn_application.h"

/* Including external dependencies */
#include "GeneralString.h"

#ifdef __cplusplus
extern "C" {
#endif

/* ModuloRegistroDigitalVoto_DataHoraJE */
typedef GeneralString_t	 ModuloRegistroDigitalVoto_DataHoraJE_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_ModuloRegistroDigitalVoto_DataHoraJE_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_ModuloRegistroDigitalVoto_DataHoraJE;
asn_struct_free_f ModuloRegistroDigitalVoto_DataHoraJE_free;
asn_struct_print_f ModuloRegistroDigitalVoto_DataHoraJE_print;
asn_constr_check_f ModuloRegistroDigitalVoto_DataHoraJE_constraint;
ber_type_decoder_f ModuloRegistroDigitalVoto_DataHoraJE_decode_ber;
der_type_encoder_f ModuloRegistroDigitalVoto_DataHoraJE_encode_der;
xer_type_decoder_f ModuloRegistroDigitalVoto_DataHoraJE_decode_xer;
xer_type_encoder_f ModuloRegistroDigitalVoto_DataHoraJE_encode_xer;
jer_type_encoder_f ModuloRegistroDigitalVoto_DataHoraJE_encode_jer;
oer_type_decoder_f ModuloRegistroDigitalVoto_DataHoraJE_decode_oer;
oer_type_encoder_f ModuloRegistroDigitalVoto_DataHoraJE_encode_oer;
per_type_decoder_f ModuloRegistroDigitalVoto_DataHoraJE_decode_uper;
per_type_encoder_f ModuloRegistroDigitalVoto_DataHoraJE_encode_uper;
per_type_decoder_f ModuloRegistroDigitalVoto_DataHoraJE_decode_aper;
per_type_encoder_f ModuloRegistroDigitalVoto_DataHoraJE_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _ModuloRegistroDigitalVoto_DataHoraJE_H_ */
#include "asn_internal.h"
