/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ModuloBU"
 * 	found in "../../../asn/bu.asn1"
 * 	`asn1c -fline-refs -fcompound-names -fincludes-quoted`
 */

#ifndef	_ModuloBU_CargoConstitucional_H_
#define	_ModuloBU_CargoConstitucional_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeEnumerated.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ModuloBU_CargoConstitucional {
	ModuloBU_CargoConstitucional_presidente	= 1,
	ModuloBU_CargoConstitucional_vicePresidente	= 2,
	ModuloBU_CargoConstitucional_governador	= 3,
	ModuloBU_CargoConstitucional_viceGovernador	= 4,
	ModuloBU_CargoConstitucional_senador	= 5,
	ModuloBU_CargoConstitucional_deputadoFederal	= 6,
	ModuloBU_CargoConstitucional_deputadoEstadual	= 7,
	ModuloBU_CargoConstitucional_deputadoDistrital	= 8,
	ModuloBU_CargoConstitucional_primeiroSuplenteSenador	= 9,
	ModuloBU_CargoConstitucional_segundoSuplenteSenador	= 10,
	ModuloBU_CargoConstitucional_prefeito	= 11,
	ModuloBU_CargoConstitucional_vicePrefeito	= 12,
	ModuloBU_CargoConstitucional_vereador	= 13
} e_ModuloBU_CargoConstitucional;

/* ModuloBU_CargoConstitucional */
typedef long	 ModuloBU_CargoConstitucional_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_ModuloBU_CargoConstitucional_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_ModuloBU_CargoConstitucional;
extern const asn_INTEGER_specifics_t asn_SPC_ModuloBU_CargoConstitucional_specs_1;
asn_struct_free_f ModuloBU_CargoConstitucional_free;
asn_struct_print_f ModuloBU_CargoConstitucional_print;
asn_constr_check_f ModuloBU_CargoConstitucional_constraint;
ber_type_decoder_f ModuloBU_CargoConstitucional_decode_ber;
der_type_encoder_f ModuloBU_CargoConstitucional_encode_der;
xer_type_decoder_f ModuloBU_CargoConstitucional_decode_xer;
xer_type_encoder_f ModuloBU_CargoConstitucional_encode_xer;
jer_type_encoder_f ModuloBU_CargoConstitucional_encode_jer;
oer_type_decoder_f ModuloBU_CargoConstitucional_decode_oer;
oer_type_encoder_f ModuloBU_CargoConstitucional_encode_oer;
per_type_decoder_f ModuloBU_CargoConstitucional_decode_uper;
per_type_encoder_f ModuloBU_CargoConstitucional_encode_uper;
per_type_decoder_f ModuloBU_CargoConstitucional_decode_aper;
per_type_encoder_f ModuloBU_CargoConstitucional_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _ModuloBU_CargoConstitucional_H_ */
#include "asn_internal.h"
