/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ModuloRegistroDigitalVoto"
 * 	found in "../../../asn/rdv.asn1"
 * 	`asn1c -fline-refs -fcompound-names -fincludes-quoted`
 */

#ifndef	_ModuloRegistroDigitalVoto_IDPleito_H_
#define	_ModuloRegistroDigitalVoto_IDPleito_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"

#ifdef __cplusplus
extern "C" {
#endif

/* ModuloRegistroDigitalVoto_IDPleito */
typedef long	 ModuloRegistroDigitalVoto_IDPleito_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_ModuloRegistroDigitalVoto_IDPleito_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_ModuloRegistroDigitalVoto_IDPleito;
asn_struct_free_f ModuloRegistroDigitalVoto_IDPleito_free;
asn_struct_print_f ModuloRegistroDigitalVoto_IDPleito_print;
asn_constr_check_f ModuloRegistroDigitalVoto_IDPleito_constraint;
ber_type_decoder_f ModuloRegistroDigitalVoto_IDPleito_decode_ber;
der_type_encoder_f ModuloRegistroDigitalVoto_IDPleito_encode_der;
xer_type_decoder_f ModuloRegistroDigitalVoto_IDPleito_decode_xer;
xer_type_encoder_f ModuloRegistroDigitalVoto_IDPleito_encode_xer;
jer_type_encoder_f ModuloRegistroDigitalVoto_IDPleito_encode_jer;
oer_type_decoder_f ModuloRegistroDigitalVoto_IDPleito_decode_oer;
oer_type_encoder_f ModuloRegistroDigitalVoto_IDPleito_encode_oer;
per_type_decoder_f ModuloRegistroDigitalVoto_IDPleito_decode_uper;
per_type_encoder_f ModuloRegistroDigitalVoto_IDPleito_encode_uper;
per_type_decoder_f ModuloRegistroDigitalVoto_IDPleito_decode_aper;
per_type_encoder_f ModuloRegistroDigitalVoto_IDPleito_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _ModuloRegistroDigitalVoto_IDPleito_H_ */
#include "asn_internal.h"
