/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ModuloBU"
 * 	found in "../../../asn/bu.asn1"
 * 	`asn1c -fline-refs -fcompound-names -fincludes-quoted`
 */

#ifndef	_ModuloBU_NumeroSerieFlash_H_
#define	_ModuloBU_NumeroSerieFlash_H_


#include "asn_application.h"

/* Including external dependencies */
#include "OCTET_STRING.h"

#ifdef __cplusplus
extern "C" {
#endif

/* ModuloBU_NumeroSerieFlash */
typedef OCTET_STRING_t	 ModuloBU_NumeroSerieFlash_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_ModuloBU_NumeroSerieFlash_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_ModuloBU_NumeroSerieFlash;
asn_struct_free_f ModuloBU_NumeroSerieFlash_free;
asn_struct_print_f ModuloBU_NumeroSerieFlash_print;
asn_constr_check_f ModuloBU_NumeroSerieFlash_constraint;
ber_type_decoder_f ModuloBU_NumeroSerieFlash_decode_ber;
der_type_encoder_f ModuloBU_NumeroSerieFlash_encode_der;
xer_type_decoder_f ModuloBU_NumeroSerieFlash_decode_xer;
xer_type_encoder_f ModuloBU_NumeroSerieFlash_encode_xer;
jer_type_encoder_f ModuloBU_NumeroSerieFlash_encode_jer;
oer_type_decoder_f ModuloBU_NumeroSerieFlash_decode_oer;
oer_type_encoder_f ModuloBU_NumeroSerieFlash_encode_oer;
per_type_decoder_f ModuloBU_NumeroSerieFlash_decode_uper;
per_type_encoder_f ModuloBU_NumeroSerieFlash_encode_uper;
per_type_decoder_f ModuloBU_NumeroSerieFlash_decode_aper;
per_type_encoder_f ModuloBU_NumeroSerieFlash_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _ModuloBU_NumeroSerieFlash_H_ */
#include "asn_internal.h"
