/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ModuloRegistroDigitalVoto"
 * 	found in "../../../asn/rdv.asn1"
 * 	`asn1c -fline-refs -fcompound-names -fincludes-quoted`
 */

#ifndef	_ModuloRegistroDigitalVoto_TipoArquivo_H_
#define	_ModuloRegistroDigitalVoto_TipoArquivo_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeEnumerated.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ModuloRegistroDigitalVoto_TipoArquivo {
	ModuloRegistroDigitalVoto_TipoArquivo_votacaoUE	= 1,
	ModuloRegistroDigitalVoto_TipoArquivo_votacaoRED	= 2,
	ModuloRegistroDigitalVoto_TipoArquivo_saMistaMRParcialCedula	= 3,
	ModuloRegistroDigitalVoto_TipoArquivo_saMistaBUImpressoCedula	= 4,
	ModuloRegistroDigitalVoto_TipoArquivo_saManual	= 5,
	ModuloRegistroDigitalVoto_TipoArquivo_saEletronica	= 6
} e_ModuloRegistroDigitalVoto_TipoArquivo;

/* ModuloRegistroDigitalVoto_TipoArquivo */
typedef long	 ModuloRegistroDigitalVoto_TipoArquivo_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_ModuloRegistroDigitalVoto_TipoArquivo_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_ModuloRegistroDigitalVoto_TipoArquivo;
extern const asn_INTEGER_specifics_t asn_SPC_ModuloRegistroDigitalVoto_TipoArquivo_specs_1;
asn_struct_free_f ModuloRegistroDigitalVoto_TipoArquivo_free;
asn_struct_print_f ModuloRegistroDigitalVoto_TipoArquivo_print;
asn_constr_check_f ModuloRegistroDigitalVoto_TipoArquivo_constraint;
ber_type_decoder_f ModuloRegistroDigitalVoto_TipoArquivo_decode_ber;
der_type_encoder_f ModuloRegistroDigitalVoto_TipoArquivo_encode_der;
xer_type_decoder_f ModuloRegistroDigitalVoto_TipoArquivo_decode_xer;
xer_type_encoder_f ModuloRegistroDigitalVoto_TipoArquivo_encode_xer;
jer_type_encoder_f ModuloRegistroDigitalVoto_TipoArquivo_encode_jer;
oer_type_decoder_f ModuloRegistroDigitalVoto_TipoArquivo_decode_oer;
oer_type_encoder_f ModuloRegistroDigitalVoto_TipoArquivo_encode_oer;
per_type_decoder_f ModuloRegistroDigitalVoto_TipoArquivo_decode_uper;
per_type_encoder_f ModuloRegistroDigitalVoto_TipoArquivo_encode_uper;
per_type_decoder_f ModuloRegistroDigitalVoto_TipoArquivo_decode_aper;
per_type_encoder_f ModuloRegistroDigitalVoto_TipoArquivo_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _ModuloRegistroDigitalVoto_TipoArquivo_H_ */
#include "asn_internal.h"
