/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ModuloRegistroDigitalVoto"
 * 	found in "../../../asn/rdv.asn1"
 * 	`asn1c -fline-refs -fcompound-names -fincludes-quoted`
 */

#ifndef	_ModuloRegistroDigitalVoto_IDEleitoral_H_
#define	_ModuloRegistroDigitalVoto_IDEleitoral_H_


#include "asn_application.h"

/* Including external dependencies */
#include "ModuloRegistroDigitalVoto_IDProcessoEleitoral.h"
#include "ModuloRegistroDigitalVoto_IDPleito.h"
#include "ModuloRegistroDigitalVoto_IDEleicao.h"
#include "constr_CHOICE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ModuloRegistroDigitalVoto_IDEleitoral_PR {
	ModuloRegistroDigitalVoto_IDEleitoral_PR_NOTHING,	/* No components present */
	ModuloRegistroDigitalVoto_IDEleitoral_PR_idProcessoEleitoral,
	ModuloRegistroDigitalVoto_IDEleitoral_PR_idPleito,
	ModuloRegistroDigitalVoto_IDEleitoral_PR_idEleicao
} ModuloRegistroDigitalVoto_IDEleitoral_PR;

/* ModuloRegistroDigitalVoto_IDEleitoral */
typedef struct ModuloRegistroDigitalVoto_IDEleitoral {
	ModuloRegistroDigitalVoto_IDEleitoral_PR present;
	union ModuloRegistroDigitalVoto_IDEleitoral_u {
		ModuloRegistroDigitalVoto_IDProcessoEleitoral_t	 idProcessoEleitoral;
		ModuloRegistroDigitalVoto_IDPleito_t	 idPleito;
		ModuloRegistroDigitalVoto_IDEleicao_t	 idEleicao;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ModuloRegistroDigitalVoto_IDEleitoral_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ModuloRegistroDigitalVoto_IDEleitoral;
extern asn_CHOICE_specifics_t asn_SPC_ModuloRegistroDigitalVoto_IDEleitoral_specs_1;
extern asn_TYPE_member_t asn_MBR_ModuloRegistroDigitalVoto_IDEleitoral_1[3];
extern asn_per_constraints_t asn_PER_type_ModuloRegistroDigitalVoto_IDEleitoral_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _ModuloRegistroDigitalVoto_IDEleitoral_H_ */
#include "asn_internal.h"
