/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ModuloBU"
 * 	found in "../../../asn/bu.asn1"
 * 	`asn1c -fline-refs -fcompound-names -fincludes-quoted`
 */

#ifndef	_ModuloBU_IDEleitoral_H_
#define	_ModuloBU_IDEleitoral_H_


#include "asn_application.h"

/* Including external dependencies */
#include "ModuloBU_IDProcessoEleitoral.h"
#include "ModuloBU_IDPleito.h"
#include "ModuloBU_IDEleicao.h"
#include "constr_CHOICE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ModuloBU_IDEleitoral_PR {
	ModuloBU_IDEleitoral_PR_NOTHING,	/* No components present */
	ModuloBU_IDEleitoral_PR_idProcessoEleitoral,
	ModuloBU_IDEleitoral_PR_idPleito,
	ModuloBU_IDEleitoral_PR_idEleicao
} ModuloBU_IDEleitoral_PR;

/* ModuloBU_IDEleitoral */
typedef struct ModuloBU_IDEleitoral {
	ModuloBU_IDEleitoral_PR present;
	union ModuloBU_IDEleitoral_u {
		ModuloBU_IDProcessoEleitoral_t	 idProcessoEleitoral;
		ModuloBU_IDPleito_t	 idPleito;
		ModuloBU_IDEleicao_t	 idEleicao;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ModuloBU_IDEleitoral_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ModuloBU_IDEleitoral;
extern asn_CHOICE_specifics_t asn_SPC_ModuloBU_IDEleitoral_specs_1;
extern asn_TYPE_member_t asn_MBR_ModuloBU_IDEleitoral_1[3];
extern asn_per_constraints_t asn_PER_type_ModuloBU_IDEleitoral_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _ModuloBU_IDEleitoral_H_ */
#include "asn_internal.h"
