/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ModuloBU"
 * 	found in "../../../asn/bu.asn1"
 * 	`asn1c -fline-refs -fcompound-names -fincludes-quoted`
 */

#include "ModuloBU_MotivoApuracaoMistaComMR.h"

/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
#if !defined(ASN_DISABLE_OER_SUPPORT)
static asn_oer_constraints_t asn_OER_type_ModuloBU_MotivoApuracaoMistaComMR_constr_1 CC_NOTUSED = {
	{ 0, 0 },
	-1};
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
asn_per_constraints_t asn_PER_type_ModuloBU_MotivoApuracaoMistaComMR_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 3,  3,  0,  6 }	/* (0..6) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
static const asn_INTEGER_enum_map_t asn_MAP_ModuloBU_MotivoApuracaoMistaComMR_value2enum_1[] = {
	{ 1,	26,	"naoObteveExitoContingencia" },
	{ 2,	33,	"indisponibilidadeUrnaContingencia" },
	{ 3,	34,	"indisponibilidadeFlashContingencia" },
	{ 4,	23,	"problemaEnergiaEletrica" },
	{ 5,	24,	"naoFoiPossivelTrocarUrna" },
	{ 6,	25,	"naoFoiSolicitadaTrocaUrna" },
	{ 99,	6,	"outros" }
};
static const unsigned int asn_MAP_ModuloBU_MotivoApuracaoMistaComMR_enum2value_1[] = {
	2,	/* indisponibilidadeFlashContingencia(3) */
	1,	/* indisponibilidadeUrnaContingencia(2) */
	4,	/* naoFoiPossivelTrocarUrna(5) */
	5,	/* naoFoiSolicitadaTrocaUrna(6) */
	0,	/* naoObteveExitoContingencia(1) */
	6,	/* outros(99) */
	3	/* problemaEnergiaEletrica(4) */
};
const asn_INTEGER_specifics_t asn_SPC_ModuloBU_MotivoApuracaoMistaComMR_specs_1 = {
	asn_MAP_ModuloBU_MotivoApuracaoMistaComMR_value2enum_1,	/* "tag" => N; sorted by tag */
	asn_MAP_ModuloBU_MotivoApuracaoMistaComMR_enum2value_1,	/* N => "tag"; sorted by N */
	7,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_ModuloBU_MotivoApuracaoMistaComMR_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
asn_TYPE_descriptor_t asn_DEF_ModuloBU_MotivoApuracaoMistaComMR = {
	"MotivoApuracaoMistaComMR",
	"MotivoApuracaoMistaComMR",
	&asn_OP_NativeEnumerated,
	asn_DEF_ModuloBU_MotivoApuracaoMistaComMR_tags_1,
	sizeof(asn_DEF_ModuloBU_MotivoApuracaoMistaComMR_tags_1)
		/sizeof(asn_DEF_ModuloBU_MotivoApuracaoMistaComMR_tags_1[0]), /* 1 */
	asn_DEF_ModuloBU_MotivoApuracaoMistaComMR_tags_1,	/* Same as above */
	sizeof(asn_DEF_ModuloBU_MotivoApuracaoMistaComMR_tags_1)
		/sizeof(asn_DEF_ModuloBU_MotivoApuracaoMistaComMR_tags_1[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		&asn_OER_type_ModuloBU_MotivoApuracaoMistaComMR_constr_1,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_ModuloBU_MotivoApuracaoMistaComMR_constr_1,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		NativeEnumerated_constraint
	},
	0, 0,	/* Defined elsewhere */
	&asn_SPC_ModuloBU_MotivoApuracaoMistaComMR_specs_1	/* Additional specs */
};

