/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ModuloBU"
 * 	found in "../../../asn/bu.asn1"
 * 	`asn1c -fline-refs -fcompound-names -fincludes-quoted`
 */

#ifndef	_ModuloBU_IdentificacaoUrna_H_
#define	_ModuloBU_IdentificacaoUrna_H_


#include "asn_application.h"

/* Including external dependencies */
#include "ModuloBU_IdentificacaoSecaoEleitoral.h"
#include "ModuloBU_IdentificacaoContingencia.h"
#include "constr_CHOICE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ModuloBU_IdentificacaoUrna_PR {
	ModuloBU_IdentificacaoUrna_PR_NOTHING,	/* No components present */
	ModuloBU_IdentificacaoUrna_PR_identificacaoSecaoEleitoral,
	ModuloBU_IdentificacaoUrna_PR_identificacaoContingencia
} ModuloBU_IdentificacaoUrna_PR;

/* ModuloBU_IdentificacaoUrna */
typedef struct ModuloBU_IdentificacaoUrna {
	ModuloBU_IdentificacaoUrna_PR present;
	union ModuloBU_IdentificacaoUrna_u {
		ModuloBU_IdentificacaoSecaoEleitoral_t	 identificacaoSecaoEleitoral;
		ModuloBU_IdentificacaoContingencia_t	 identificacaoContingencia;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ModuloBU_IdentificacaoUrna_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ModuloBU_IdentificacaoUrna;
extern asn_CHOICE_specifics_t asn_SPC_ModuloBU_IdentificacaoUrna_specs_1;
extern asn_TYPE_member_t asn_MBR_ModuloBU_IdentificacaoUrna_1[2];
extern asn_per_constraints_t asn_PER_type_ModuloBU_IdentificacaoUrna_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _ModuloBU_IdentificacaoUrna_H_ */
#include "asn_internal.h"
