/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ModuloRegistroDigitalVoto"
 * 	found in "../../../asn/rdv.asn1"
 * 	`asn1c -fline-refs -fcompound-names -fincludes-quoted`
 */

#include "ModuloRegistroDigitalVoto_TipoVoto.h"

/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
#if !defined(ASN_DISABLE_OER_SUPPORT)
static asn_oer_constraints_t asn_OER_type_ModuloRegistroDigitalVoto_TipoVoto_constr_1 CC_NOTUSED = {
	{ 0, 0 },
	-1};
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
asn_per_constraints_t asn_PER_type_ModuloRegistroDigitalVoto_TipoVoto_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 4,  4,  0,  8 }	/* (0..8) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
static const asn_INTEGER_enum_map_t asn_MAP_ModuloRegistroDigitalVoto_TipoVoto_value2enum_1[] = {
	{ 1,	7,	"legenda" },
	{ 2,	7,	"nominal" },
	{ 3,	6,	"branco" },
	{ 4,	4,	"nulo" },
	{ 5,	19,	"brancoAposSuspensao" },
	{ 6,	17,	"nuloAposSuspensao" },
	{ 7,	16,	"nuloPorRepeticao" },
	{ 8,	21,	"nuloCargoSemCandidato" },
	{ 9,	34,	"nuloAposSuspensaoCargoSemCandidato" }
};
static const unsigned int asn_MAP_ModuloRegistroDigitalVoto_TipoVoto_enum2value_1[] = {
	2,	/* branco(3) */
	4,	/* brancoAposSuspensao(5) */
	0,	/* legenda(1) */
	1,	/* nominal(2) */
	3,	/* nulo(4) */
	5,	/* nuloAposSuspensao(6) */
	8,	/* nuloAposSuspensaoCargoSemCandidato(9) */
	7,	/* nuloCargoSemCandidato(8) */
	6	/* nuloPorRepeticao(7) */
};
const asn_INTEGER_specifics_t asn_SPC_ModuloRegistroDigitalVoto_TipoVoto_specs_1 = {
	asn_MAP_ModuloRegistroDigitalVoto_TipoVoto_value2enum_1,	/* "tag" => N; sorted by tag */
	asn_MAP_ModuloRegistroDigitalVoto_TipoVoto_enum2value_1,	/* N => "tag"; sorted by N */
	9,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_ModuloRegistroDigitalVoto_TipoVoto_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
asn_TYPE_descriptor_t asn_DEF_ModuloRegistroDigitalVoto_TipoVoto = {
	"TipoVoto",
	"TipoVoto",
	&asn_OP_NativeEnumerated,
	asn_DEF_ModuloRegistroDigitalVoto_TipoVoto_tags_1,
	sizeof(asn_DEF_ModuloRegistroDigitalVoto_TipoVoto_tags_1)
		/sizeof(asn_DEF_ModuloRegistroDigitalVoto_TipoVoto_tags_1[0]), /* 1 */
	asn_DEF_ModuloRegistroDigitalVoto_TipoVoto_tags_1,	/* Same as above */
	sizeof(asn_DEF_ModuloRegistroDigitalVoto_TipoVoto_tags_1)
		/sizeof(asn_DEF_ModuloRegistroDigitalVoto_TipoVoto_tags_1[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		&asn_OER_type_ModuloRegistroDigitalVoto_TipoVoto_constr_1,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_ModuloRegistroDigitalVoto_TipoVoto_constr_1,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		NativeEnumerated_constraint
	},
	0, 0,	/* Defined elsewhere */
	&asn_SPC_ModuloRegistroDigitalVoto_TipoVoto_specs_1	/* Additional specs */
};

