/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ModuloBU"
 * 	found in "../../../asn/bu.asn1"
 * 	`asn1c -fline-refs -fcompound-names -fincludes-quoted`
 */

#ifndef	_ModuloBU_ApuracaoEletronica_H_
#define	_ModuloBU_ApuracaoEletronica_H_


#include "asn_application.h"

/* Including external dependencies */
#include "ModuloBU_TipoApuracao.h"
#include "ModuloBU_MotivoApuracaoEletronica.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* ModuloBU_ApuracaoEletronica */
typedef struct ModuloBU_ApuracaoEletronica {
	ModuloBU_TipoApuracao_t	 tipoapuracao;
	ModuloBU_MotivoApuracaoEletronica_t	 motivoApuracao;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ModuloBU_ApuracaoEletronica_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ModuloBU_ApuracaoEletronica;
extern asn_SEQUENCE_specifics_t asn_SPC_ModuloBU_ApuracaoEletronica_specs_1;
extern asn_TYPE_member_t asn_MBR_ModuloBU_ApuracaoEletronica_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _ModuloBU_ApuracaoEletronica_H_ */
#include "asn_internal.h"
