/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ModuloRegistroDigitalVoto"
 * 	found in "../../../asn/rdv.asn1"
 * 	`asn1c -fline-refs -fcompound-names -fincludes-quoted`
 */

#ifndef	_ModuloRegistroDigitalVoto_TipoVoto_H_
#define	_ModuloRegistroDigitalVoto_TipoVoto_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeEnumerated.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ModuloRegistroDigitalVoto_TipoVoto {
	ModuloRegistroDigitalVoto_TipoVoto_legenda	= 1,
	ModuloRegistroDigitalVoto_TipoVoto_nominal	= 2,
	ModuloRegistroDigitalVoto_TipoVoto_branco	= 3,
	ModuloRegistroDigitalVoto_TipoVoto_nulo	= 4,
	ModuloRegistroDigitalVoto_TipoVoto_brancoAposSuspensao	= 5,
	ModuloRegistroDigitalVoto_TipoVoto_nuloAposSuspensao	= 6,
	ModuloRegistroDigitalVoto_TipoVoto_nuloPorRepeticao	= 7,
	ModuloRegistroDigitalVoto_TipoVoto_nuloCargoSemCandidato	= 8,
	ModuloRegistroDigitalVoto_TipoVoto_nuloAposSuspensaoCargoSemCandidato	= 9
} e_ModuloRegistroDigitalVoto_TipoVoto;

/* ModuloRegistroDigitalVoto_TipoVoto */
typedef long	 ModuloRegistroDigitalVoto_TipoVoto_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_ModuloRegistroDigitalVoto_TipoVoto_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_ModuloRegistroDigitalVoto_TipoVoto;
extern const asn_INTEGER_specifics_t asn_SPC_ModuloRegistroDigitalVoto_TipoVoto_specs_1;
asn_struct_free_f ModuloRegistroDigitalVoto_TipoVoto_free;
asn_struct_print_f ModuloRegistroDigitalVoto_TipoVoto_print;
asn_constr_check_f ModuloRegistroDigitalVoto_TipoVoto_constraint;
ber_type_decoder_f ModuloRegistroDigitalVoto_TipoVoto_decode_ber;
der_type_encoder_f ModuloRegistroDigitalVoto_TipoVoto_encode_der;
xer_type_decoder_f ModuloRegistroDigitalVoto_TipoVoto_decode_xer;
xer_type_encoder_f ModuloRegistroDigitalVoto_TipoVoto_encode_xer;
jer_type_encoder_f ModuloRegistroDigitalVoto_TipoVoto_encode_jer;
oer_type_decoder_f ModuloRegistroDigitalVoto_TipoVoto_decode_oer;
oer_type_encoder_f ModuloRegistroDigitalVoto_TipoVoto_encode_oer;
per_type_decoder_f ModuloRegistroDigitalVoto_TipoVoto_decode_uper;
per_type_encoder_f ModuloRegistroDigitalVoto_TipoVoto_encode_uper;
per_type_decoder_f ModuloRegistroDigitalVoto_TipoVoto_decode_aper;
per_type_encoder_f ModuloRegistroDigitalVoto_TipoVoto_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _ModuloRegistroDigitalVoto_TipoVoto_H_ */
#include "asn_internal.h"
