/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ModuloRegistroDigitalVoto"
 * 	found in "../../../asn/rdv.asn1"
 * 	`asn1c -fline-refs -fcompound-names -fincludes-quoted`
 */

#ifndef	_ModuloRegistroDigitalVoto_Carga_H_
#define	_ModuloRegistroDigitalVoto_Carga_H_


#include "asn_application.h"

/* Including external dependencies */
#include "ModuloRegistroDigitalVoto_NumeroInternoUrna.h"
#include "ModuloRegistroDigitalVoto_NumeroSerieFlash.h"
#include "ModuloRegistroDigitalVoto_DataHoraJE.h"
#include "GeneralString.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* ModuloRegistroDigitalVoto_Carga */
typedef struct ModuloRegistroDigitalVoto_Carga {
	ModuloRegistroDigitalVoto_NumeroInternoUrna_t	 numeroInternoUrna;
	ModuloRegistroDigitalVoto_NumeroSerieFlash_t	 numeroSerieFC;
	ModuloRegistroDigitalVoto_DataHoraJE_t	 dataHoraCarga;
	GeneralString_t	 codigoCarga;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ModuloRegistroDigitalVoto_Carga_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ModuloRegistroDigitalVoto_Carga;
extern asn_SEQUENCE_specifics_t asn_SPC_ModuloRegistroDigitalVoto_Carga_specs_1;
extern asn_TYPE_member_t asn_MBR_ModuloRegistroDigitalVoto_Carga_1[4];

#ifdef __cplusplus
}
#endif

#endif	/* _ModuloRegistroDigitalVoto_Carga_H_ */
#include "asn_internal.h"
