/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ModuloAssinaturaResultado"
 * 	found in "../../../asn/assinatura.asn1"
 * 	`asn1c -fline-refs -fcompound-names -fincludes-quoted`
 */

#include "ModuloAssinaturaResultado_DataHoraJE.h"

int
ModuloAssinaturaResultado_DataHoraJE_constraint(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	const GeneralString_t *st = (const GeneralString_t *)sptr;
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	size = st->size;
	
	if((size == 15UL)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

/*
 * This type is implemented using GeneralString,
 * so here we adjust the DEF accordingly.
 */
#if !defined(ASN_DISABLE_OER_SUPPORT)
static asn_oer_constraints_t asn_OER_type_ModuloAssinaturaResultado_DataHoraJE_constr_1 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(0..MAX)) */};
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
asn_per_constraints_t asn_PER_type_ModuloAssinaturaResultado_DataHoraJE_constr_1 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
static const ber_tlv_tag_t asn_DEF_ModuloAssinaturaResultado_DataHoraJE_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (27 << 2))
};
asn_TYPE_descriptor_t asn_DEF_ModuloAssinaturaResultado_DataHoraJE = {
	"DataHoraJE",
	"DataHoraJE",
	&asn_OP_GeneralString,
	asn_DEF_ModuloAssinaturaResultado_DataHoraJE_tags_1,
	sizeof(asn_DEF_ModuloAssinaturaResultado_DataHoraJE_tags_1)
		/sizeof(asn_DEF_ModuloAssinaturaResultado_DataHoraJE_tags_1[0]), /* 1 */
	asn_DEF_ModuloAssinaturaResultado_DataHoraJE_tags_1,	/* Same as above */
	sizeof(asn_DEF_ModuloAssinaturaResultado_DataHoraJE_tags_1)
		/sizeof(asn_DEF_ModuloAssinaturaResultado_DataHoraJE_tags_1[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		&asn_OER_type_ModuloAssinaturaResultado_DataHoraJE_constr_1,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_ModuloAssinaturaResultado_DataHoraJE_constr_1,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		ModuloAssinaturaResultado_DataHoraJE_constraint
	},
	0, 0,	/* No members */
	0	/* No specifics */
};

