/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ModuloRegistroDigitalVoto"
 * 	found in "../../../asn/rdv.asn1"
 * 	`asn1c -fline-refs -fcompound-names -fincludes-quoted`
 */

#ifndef	_ModuloRegistroDigitalVoto_Urna_H_
#define	_ModuloRegistroDigitalVoto_Urna_H_


#include "asn_application.h"

/* Including external dependencies */
#include "ModuloRegistroDigitalVoto_TipoUrna.h"
#include "GeneralString.h"
#include "ModuloRegistroDigitalVoto_CorrespondenciaResultado.h"
#include "ModuloRegistroDigitalVoto_TipoArquivo.h"
#include "ModuloRegistroDigitalVoto_NumeroSerieFlash.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct TipoApuracaoSA;

/* ModuloRegistroDigitalVoto_Urna */
typedef struct ModuloRegistroDigitalVoto_Urna {
	ModuloRegistroDigitalVoto_TipoUrna_t	 tipoUrna;
	GeneralString_t	 versaoVotacao;
	ModuloRegistroDigitalVoto_CorrespondenciaResultado_t	 correspondenciaResultado;
	ModuloRegistroDigitalVoto_TipoArquivo_t	 tipoArquivo;
	ModuloRegistroDigitalVoto_NumeroSerieFlash_t	 numeroSerieFV;
	struct TipoApuracaoSA	*motivoUtilizacaoSA;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ModuloRegistroDigitalVoto_Urna_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ModuloRegistroDigitalVoto_Urna;
extern asn_SEQUENCE_specifics_t asn_SPC_ModuloRegistroDigitalVoto_Urna_specs_1;
extern asn_TYPE_member_t asn_MBR_ModuloRegistroDigitalVoto_Urna_1[6];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "ModuloRegistroDigitalVoto_TipoApuracaoSA.h"

#endif	/* _ModuloRegistroDigitalVoto_Urna_H_ */
#include "asn_internal.h"
