/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ModuloBU"
 * 	found in "../../../asn/bu.asn1"
 * 	`asn1c -fline-refs -fcompound-names -fincludes-quoted`
 */

#include "ModuloBU_ApuracaoTotalmenteManualDigitacaoAE.h"

asn_TYPE_member_t asn_MBR_ModuloBU_ApuracaoTotalmenteManualDigitacaoAE_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ModuloBU_ApuracaoTotalmenteManualDigitacaoAE, tipoapuracao),
		(ASN_TAG_CLASS_UNIVERSAL | (10 << 2)),
		0,
		&asn_DEF_ModuloBU_TipoApuracao,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"tipoapuracao"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ModuloBU_ApuracaoTotalmenteManualDigitacaoAE, motivoApuracao),
		(ASN_TAG_CLASS_UNIVERSAL | (10 << 2)),
		0,
		&asn_DEF_ModuloBU_MotivoApuracaoManual,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"motivoApuracao"
		},
};
static const ber_tlv_tag_t asn_DEF_ModuloBU_ApuracaoTotalmenteManualDigitacaoAE_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_ModuloBU_ApuracaoTotalmenteManualDigitacaoAE_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (10 << 2)), 0, 0, 1 }, /* tipoapuracaoat 185 */
    { (ASN_TAG_CLASS_UNIVERSAL | (10 << 2)), 1, -1, 0 } /* motivoApuracaoat 187 */
};
asn_SEQUENCE_specifics_t asn_SPC_ModuloBU_ApuracaoTotalmenteManualDigitacaoAE_specs_1 = {
	sizeof(struct ModuloBU_ApuracaoTotalmenteManualDigitacaoAE),
	offsetof(struct ModuloBU_ApuracaoTotalmenteManualDigitacaoAE, _asn_ctx),
	asn_MAP_ModuloBU_ApuracaoTotalmenteManualDigitacaoAE_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_ModuloBU_ApuracaoTotalmenteManualDigitacaoAE = {
	"ApuracaoTotalmenteManualDigitacaoAE",
	"ApuracaoTotalmenteManualDigitacaoAE",
	&asn_OP_SEQUENCE,
	asn_DEF_ModuloBU_ApuracaoTotalmenteManualDigitacaoAE_tags_1,
	sizeof(asn_DEF_ModuloBU_ApuracaoTotalmenteManualDigitacaoAE_tags_1)
		/sizeof(asn_DEF_ModuloBU_ApuracaoTotalmenteManualDigitacaoAE_tags_1[0]), /* 1 */
	asn_DEF_ModuloBU_ApuracaoTotalmenteManualDigitacaoAE_tags_1,	/* Same as above */
	sizeof(asn_DEF_ModuloBU_ApuracaoTotalmenteManualDigitacaoAE_tags_1)
		/sizeof(asn_DEF_ModuloBU_ApuracaoTotalmenteManualDigitacaoAE_tags_1[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_ModuloBU_ApuracaoTotalmenteManualDigitacaoAE_1,
	2,	/* Elements count */
	&asn_SPC_ModuloBU_ApuracaoTotalmenteManualDigitacaoAE_specs_1	/* Additional specs */
};

