/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ModuloBU"
 * 	found in "../../../asn/bu.asn1"
 * 	`asn1c -fline-refs -fcompound-names -fincludes-quoted`
 */

#ifndef	_ModuloBU_CodigoCargoConsulta_H_
#define	_ModuloBU_CodigoCargoConsulta_H_


#include "asn_application.h"

/* Including external dependencies */
#include "ModuloBU_CargoConstitucional.h"
#include "ModuloBU_NumeroCargoConsultaLivre.h"
#include "constr_CHOICE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ModuloBU_CodigoCargoConsulta_PR {
	ModuloBU_CodigoCargoConsulta_PR_NOTHING,	/* No components present */
	ModuloBU_CodigoCargoConsulta_PR_cargoConstitucional,
	ModuloBU_CodigoCargoConsulta_PR_numeroCargoConsultaLivre
} ModuloBU_CodigoCargoConsulta_PR;

/* ModuloBU_CodigoCargoConsulta */
typedef struct ModuloBU_CodigoCargoConsulta {
	ModuloBU_CodigoCargoConsulta_PR present;
	union ModuloBU_CodigoCargoConsulta_u {
		ModuloBU_CargoConstitucional_t	 cargoConstitucional;
		ModuloBU_NumeroCargoConsultaLivre_t	 numeroCargoConsultaLivre;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ModuloBU_CodigoCargoConsulta_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ModuloBU_CodigoCargoConsulta;
extern asn_CHOICE_specifics_t asn_SPC_ModuloBU_CodigoCargoConsulta_specs_1;
extern asn_TYPE_member_t asn_MBR_ModuloBU_CodigoCargoConsulta_1[2];
extern asn_per_constraints_t asn_PER_type_ModuloBU_CodigoCargoConsulta_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _ModuloBU_CodigoCargoConsulta_H_ */
#include "asn_internal.h"
