/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ModuloBU"
 * 	found in "../../../asn/bu.asn1"
 * 	`asn1c -fline-refs -fcompound-names -fincludes-quoted`
 */

#ifndef	_NumeroVotavel_H_
#define	_NumeroVotavel_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"

#ifdef __cplusplus
extern "C" {
#endif

/* NumeroVotavel */
typedef long	 NumeroVotavel_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_NumeroVotavel_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_NumeroVotavel;
asn_struct_free_f NumeroVotavel_free;
asn_struct_print_f NumeroVotavel_print;
asn_constr_check_f NumeroVotavel_constraint;
ber_type_decoder_f NumeroVotavel_decode_ber;
der_type_encoder_f NumeroVotavel_encode_der;
xer_type_decoder_f NumeroVotavel_decode_xer;
xer_type_encoder_f NumeroVotavel_encode_xer;
jer_type_encoder_f NumeroVotavel_encode_jer;
oer_type_decoder_f NumeroVotavel_decode_oer;
oer_type_encoder_f NumeroVotavel_encode_oer;
per_type_decoder_f NumeroVotavel_decode_uper;
per_type_encoder_f NumeroVotavel_encode_uper;
per_type_decoder_f NumeroVotavel_decode_aper;
per_type_encoder_f NumeroVotavel_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _NumeroVotavel_H_ */
#include "asn_internal.h"
