/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 */

struct asn_TYPE_descriptor_s;	/* Forward declaration */

extern struct asn_TYPE_descriptor_s asn_DEF_EntidadeAssinaturaResultado;
extern struct asn_TYPE_descriptor_s asn_DEF_Assinatura;
extern struct asn_TYPE_descriptor_s asn_DEF_EntidadeEnvelopeGenerico;
extern struct asn_TYPE_descriptor_s asn_DEF_EntidadeBoletimUrna;
extern struct asn_TYPE_descriptor_s asn_DEF_IdentificacaoMesaJustificativa;
extern struct asn_TYPE_descriptor_s asn_DEF_EntidadeResultadoRDV;
extern struct asn_TYPE_descriptor_s asn_DEF_EXTERNAL;


struct asn_TYPE_descriptor_s *asn_pdu_collection[] = {
	/* From module ModuloAssinaturaResultado in ../../../asn/assinatura.asn1 */
	&asn_DEF_EntidadeAssinaturaResultado,	
	&asn_DEF_Assinatura,	
	/* From module ModuloBU in ../../../asn/bu.asn1 */
	&asn_DEF_EntidadeEnvelopeGenerico,	
	&asn_DEF_EntidadeBoletimUrna,	
	&asn_DEF_IdentificacaoMesaJustificativa,	
	/* From module ModuloRegistroDigitalVoto in ../../../asn/rdv.asn1 */
	&asn_DEF_EntidadeResultadoRDV,	
	/* From module ASN1C-UsefulInformationObjectClasses in /usr/local/share/asn1c/standard-modules/ASN1C-UsefulInformationObjectClasses.asn1 */
	&asn_DEF_EXTERNAL,	
	0
};

