/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ModuloBU"
 * 	found in "../../../asn/bu.asn1"
 * 	`asn1c -fline-refs -fcompound-names -fincludes-quoted`
 */

#ifndef	_QtdEleitores_H_
#define	_QtdEleitores_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"

#ifdef __cplusplus
extern "C" {
#endif

/* QtdEleitores */
typedef long	 QtdEleitores_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_QtdEleitores_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_QtdEleitores;
asn_struct_free_f QtdEleitores_free;
asn_struct_print_f QtdEleitores_print;
asn_constr_check_f QtdEleitores_constraint;
ber_type_decoder_f QtdEleitores_decode_ber;
der_type_encoder_f QtdEleitores_encode_der;
xer_type_decoder_f QtdEleitores_decode_xer;
xer_type_encoder_f QtdEleitores_encode_xer;
jer_type_encoder_f QtdEleitores_encode_jer;
oer_type_decoder_f QtdEleitores_decode_oer;
oer_type_encoder_f QtdEleitores_encode_oer;
per_type_decoder_f QtdEleitores_decode_uper;
per_type_encoder_f QtdEleitores_encode_uper;
per_type_decoder_f QtdEleitores_decode_aper;
per_type_encoder_f QtdEleitores_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _QtdEleitores_H_ */
#include "asn_internal.h"
