/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ModuloRegistroDigitalVoto"
 * 	found in "../../../asn/rdv.asn1"
 * 	`asn1c -fline-refs -fcompound-names -fincludes-quoted`
 */

#ifndef	_QuantidadeEscolhas_H_
#define	_QuantidadeEscolhas_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"

#ifdef __cplusplus
extern "C" {
#endif

/* QuantidadeEscolhas */
typedef long	 QuantidadeEscolhas_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_QuantidadeEscolhas_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_QuantidadeEscolhas;
asn_struct_free_f QuantidadeEscolhas_free;
asn_struct_print_f QuantidadeEscolhas_print;
asn_constr_check_f QuantidadeEscolhas_constraint;
ber_type_decoder_f QuantidadeEscolhas_decode_ber;
der_type_encoder_f QuantidadeEscolhas_encode_der;
xer_type_decoder_f QuantidadeEscolhas_decode_xer;
xer_type_encoder_f QuantidadeEscolhas_encode_xer;
jer_type_encoder_f QuantidadeEscolhas_encode_jer;
oer_type_decoder_f QuantidadeEscolhas_decode_oer;
oer_type_encoder_f QuantidadeEscolhas_encode_oer;
per_type_decoder_f QuantidadeEscolhas_decode_uper;
per_type_encoder_f QuantidadeEscolhas_encode_uper;
per_type_decoder_f QuantidadeEscolhas_decode_aper;
per_type_encoder_f QuantidadeEscolhas_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _QuantidadeEscolhas_H_ */
#include "asn_internal.h"
