/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ModuloBU"
 * 	found in "../../../asn/bu.asn1"
 * 	`asn1c -fline-refs -fcompound-names -fincludes-quoted`
 */

#ifndef	_ResultadoVotacao_H_
#define	_ResultadoVotacao_H_


#include "asn_application.h"

/* Including external dependencies */
#include "TipoCargoConsulta.h"
#include "QtdEleitores.h"
#include "asn_SEQUENCE_OF.h"
#include "constr_SEQUENCE_OF.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct TotalVotosCargo;

/* ResultadoVotacao */
typedef struct ResultadoVotacao {
	TipoCargoConsulta_t	 tipoCargo;
	QtdEleitores_t	 qtdComparecimento;
	struct ResultadoVotacao__totaisVotosCargo {
		A_SEQUENCE_OF(struct TotalVotosCargo) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} totaisVotosCargo;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ResultadoVotacao_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ResultadoVotacao;
extern asn_SEQUENCE_specifics_t asn_SPC_ResultadoVotacao_specs_1;
extern asn_TYPE_member_t asn_MBR_ResultadoVotacao_1[3];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "TotalVotosCargo.h"

#endif	/* _ResultadoVotacao_H_ */
#include "asn_internal.h"
