/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ModuloBU"
 * 	found in "../../../asn/bu.asn1"
 * 	`asn1c -fline-refs -fcompound-names -fincludes-quoted`
 */

#include "ResultadoVotacaoPorEleicao.h"

static asn_TYPE_member_t asn_MBR_resultadosVotacao_4[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_ResultadoVotacao,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_resultadosVotacao_tags_4[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_resultadosVotacao_specs_4 = {
	sizeof(struct ResultadoVotacaoPorEleicao__resultadosVotacao),
	offsetof(struct ResultadoVotacaoPorEleicao__resultadosVotacao, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_resultadosVotacao_4 = {
	"resultadosVotacao",
	"resultadosVotacao",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_resultadosVotacao_tags_4,
	sizeof(asn_DEF_resultadosVotacao_tags_4)
		/sizeof(asn_DEF_resultadosVotacao_tags_4[0]), /* 1 */
	asn_DEF_resultadosVotacao_tags_4,	/* Same as above */
	sizeof(asn_DEF_resultadosVotacao_tags_4)
		/sizeof(asn_DEF_resultadosVotacao_tags_4[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_OF_constraint
	},
	asn_MBR_resultadosVotacao_4,
	1,	/* Single element */
	&asn_SPC_resultadosVotacao_specs_4	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_ResultadoVotacaoPorEleicao_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ResultadoVotacaoPorEleicao, idEleicao),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_ModuloBU_IDEleicao,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"idEleicao"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ResultadoVotacaoPorEleicao, qtdEleitoresAptos),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_QtdEleitores,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"qtdEleitoresAptos"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ResultadoVotacaoPorEleicao, resultadosVotacao),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_resultadosVotacao_4,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"resultadosVotacao"
		},
};
static const ber_tlv_tag_t asn_DEF_ResultadoVotacaoPorEleicao_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_ResultadoVotacaoPorEleicao_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 0, 0, 1 }, /* idEleicaoat 295 */
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 1, -1, 0 }, /* qtdEleitoresAptosat 296 */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 2, 0, 0 } /* resultadosVotacaoat 298 */
};
asn_SEQUENCE_specifics_t asn_SPC_ResultadoVotacaoPorEleicao_specs_1 = {
	sizeof(struct ResultadoVotacaoPorEleicao),
	offsetof(struct ResultadoVotacaoPorEleicao, _asn_ctx),
	asn_MAP_ResultadoVotacaoPorEleicao_tag2el_1,
	3,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_ResultadoVotacaoPorEleicao = {
	"ResultadoVotacaoPorEleicao",
	"ResultadoVotacaoPorEleicao",
	&asn_OP_SEQUENCE,
	asn_DEF_ResultadoVotacaoPorEleicao_tags_1,
	sizeof(asn_DEF_ResultadoVotacaoPorEleicao_tags_1)
		/sizeof(asn_DEF_ResultadoVotacaoPorEleicao_tags_1[0]), /* 1 */
	asn_DEF_ResultadoVotacaoPorEleicao_tags_1,	/* Same as above */
	sizeof(asn_DEF_ResultadoVotacaoPorEleicao_tags_1)
		/sizeof(asn_DEF_ResultadoVotacaoPorEleicao_tags_1[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_ResultadoVotacaoPorEleicao_1,
	3,	/* Elements count */
	&asn_SPC_ResultadoVotacaoPorEleicao_specs_1	/* Additional specs */
};

