/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ModuloBU"
 * 	found in "../../../asn/bu.asn1"
 * 	`asn1c -fline-refs -fcompound-names -fincludes-quoted`
 */

#ifndef	_ResultadoVotacaoPorEleicao_H_
#define	_ResultadoVotacaoPorEleicao_H_


#include "asn_application.h"

/* Including external dependencies */
#include "ModuloBU_IDEleicao.h"
#include "QtdEleitores.h"
#include "asn_SEQUENCE_OF.h"
#include "constr_SEQUENCE_OF.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ResultadoVotacao;

/* ResultadoVotacaoPorEleicao */
typedef struct ResultadoVotacaoPorEleicao {
	ModuloBU_IDEleicao_t	 idEleicao;
	QtdEleitores_t	 qtdEleitoresAptos;
	struct ResultadoVotacaoPorEleicao__resultadosVotacao {
		A_SEQUENCE_OF(struct ResultadoVotacao) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} resultadosVotacao;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ResultadoVotacaoPorEleicao_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ResultadoVotacaoPorEleicao;
extern asn_SEQUENCE_specifics_t asn_SPC_ResultadoVotacaoPorEleicao_specs_1;
extern asn_TYPE_member_t asn_MBR_ResultadoVotacaoPorEleicao_1[3];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "ResultadoVotacao.h"

#endif	/* _ResultadoVotacaoPorEleicao_H_ */
#include "asn_internal.h"
