/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ModuloBU"
 * 	found in "../../../asn/bu.asn1"
 * 	`asn1c -fline-refs -fcompound-names -fincludes-quoted`
 */

#include "ResultadoVotacao.h"

static asn_TYPE_member_t asn_MBR_totaisVotosCargo_4[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_TotalVotosCargo,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_totaisVotosCargo_tags_4[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_totaisVotosCargo_specs_4 = {
	sizeof(struct ResultadoVotacao__totaisVotosCargo),
	offsetof(struct ResultadoVotacao__totaisVotosCargo, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_totaisVotosCargo_4 = {
	"totaisVotosCargo",
	"totaisVotosCargo",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_totaisVotosCargo_tags_4,
	sizeof(asn_DEF_totaisVotosCargo_tags_4)
		/sizeof(asn_DEF_totaisVotosCargo_tags_4[0]), /* 1 */
	asn_DEF_totaisVotosCargo_tags_4,	/* Same as above */
	sizeof(asn_DEF_totaisVotosCargo_tags_4)
		/sizeof(asn_DEF_totaisVotosCargo_tags_4[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_OF_constraint
	},
	asn_MBR_totaisVotosCargo_4,
	1,	/* Single element */
	&asn_SPC_totaisVotosCargo_specs_4	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_ResultadoVotacao_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ResultadoVotacao, tipoCargo),
		(ASN_TAG_CLASS_UNIVERSAL | (10 << 2)),
		0,
		&asn_DEF_TipoCargoConsulta,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"tipoCargo"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ResultadoVotacao, qtdComparecimento),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_QtdEleitores,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"qtdComparecimento"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ResultadoVotacao, totaisVotosCargo),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_totaisVotosCargo_4,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"totaisVotosCargo"
		},
};
static const ber_tlv_tag_t asn_DEF_ResultadoVotacao_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_ResultadoVotacao_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 1, 0, 0 }, /* qtdComparecimentoat 289 */
    { (ASN_TAG_CLASS_UNIVERSAL | (10 << 2)), 0, 0, 0 }, /* tipoCargoat 288 */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 2, 0, 0 } /* totaisVotosCargoat 291 */
};
asn_SEQUENCE_specifics_t asn_SPC_ResultadoVotacao_specs_1 = {
	sizeof(struct ResultadoVotacao),
	offsetof(struct ResultadoVotacao, _asn_ctx),
	asn_MAP_ResultadoVotacao_tag2el_1,
	3,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_ResultadoVotacao = {
	"ResultadoVotacao",
	"ResultadoVotacao",
	&asn_OP_SEQUENCE,
	asn_DEF_ResultadoVotacao_tags_1,
	sizeof(asn_DEF_ResultadoVotacao_tags_1)
		/sizeof(asn_DEF_ResultadoVotacao_tags_1[0]), /* 1 */
	asn_DEF_ResultadoVotacao_tags_1,	/* Same as above */
	sizeof(asn_DEF_ResultadoVotacao_tags_1)
		/sizeof(asn_DEF_ResultadoVotacao_tags_1[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_ResultadoVotacao_1,
	3,	/* Elements count */
	&asn_SPC_ResultadoVotacao_specs_1	/* Additional specs */
};

