/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ModuloBU"
 * 	found in "../../../asn/bu.asn1"
 * 	`asn1c -fline-refs -fcompound-names -fincludes-quoted`
 */

#ifndef	_TipoCargoConsulta_H_
#define	_TipoCargoConsulta_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeEnumerated.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum TipoCargoConsulta {
	TipoCargoConsulta_majoritario	= 1,
	TipoCargoConsulta_proporcional	= 2,
	TipoCargoConsulta_consulta	= 3
} e_TipoCargoConsulta;

/* TipoCargoConsulta */
typedef long	 TipoCargoConsulta_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_TipoCargoConsulta_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_TipoCargoConsulta;
extern const asn_INTEGER_specifics_t asn_SPC_TipoCargoConsulta_specs_1;
asn_struct_free_f TipoCargoConsulta_free;
asn_struct_print_f TipoCargoConsulta_print;
asn_constr_check_f TipoCargoConsulta_constraint;
ber_type_decoder_f TipoCargoConsulta_decode_ber;
der_type_encoder_f TipoCargoConsulta_encode_der;
xer_type_decoder_f TipoCargoConsulta_decode_xer;
xer_type_encoder_f TipoCargoConsulta_encode_xer;
jer_type_encoder_f TipoCargoConsulta_encode_jer;
oer_type_decoder_f TipoCargoConsulta_decode_oer;
oer_type_encoder_f TipoCargoConsulta_encode_oer;
per_type_decoder_f TipoCargoConsulta_decode_uper;
per_type_encoder_f TipoCargoConsulta_encode_uper;
per_type_decoder_f TipoCargoConsulta_decode_aper;
per_type_encoder_f TipoCargoConsulta_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _TipoCargoConsulta_H_ */
#include "asn_internal.h"
