/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ModuloBU"
 * 	found in "../../../asn/bu.asn1"
 * 	`asn1c -fline-refs -fcompound-names -fincludes-quoted`
 */

#ifndef	_TipoEnvelope_H_
#define	_TipoEnvelope_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeEnumerated.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum TipoEnvelope {
	TipoEnvelope_envelopeBoletimUrna	= 1,
	TipoEnvelope_envelopeRegistroDigitalVoto	= 2,
	TipoEnvelope_envelopeBoletimUrnaImpresso	= 4,
	TipoEnvelope_envelopeImagemBiometria	= 5
} e_TipoEnvelope;

/* TipoEnvelope */
typedef long	 TipoEnvelope_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_TipoEnvelope_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_TipoEnvelope;
extern const asn_INTEGER_specifics_t asn_SPC_TipoEnvelope_specs_1;
asn_struct_free_f TipoEnvelope_free;
asn_struct_print_f TipoEnvelope_print;
asn_constr_check_f TipoEnvelope_constraint;
ber_type_decoder_f TipoEnvelope_decode_ber;
der_type_encoder_f TipoEnvelope_encode_der;
xer_type_decoder_f TipoEnvelope_decode_xer;
xer_type_encoder_f TipoEnvelope_encode_xer;
jer_type_encoder_f TipoEnvelope_encode_jer;
oer_type_decoder_f TipoEnvelope_decode_oer;
oer_type_encoder_f TipoEnvelope_encode_oer;
per_type_decoder_f TipoEnvelope_decode_uper;
per_type_encoder_f TipoEnvelope_encode_uper;
per_type_decoder_f TipoEnvelope_decode_aper;
per_type_encoder_f TipoEnvelope_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _TipoEnvelope_H_ */
#include "asn_internal.h"
