/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ModuloBU"
 * 	found in "../../../asn/bu.asn1"
 * 	`asn1c -fline-refs -fcompound-names -fincludes-quoted`
 */

#ifndef	_TotalVotosCargo_H_
#define	_TotalVotosCargo_H_


#include "asn_application.h"

/* Including external dependencies */
#include "ModuloBU_CodigoCargoConsulta.h"
#include "NativeInteger.h"
#include "asn_SEQUENCE_OF.h"
#include "constr_SEQUENCE_OF.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct TotalVotosVotavel;

/* TotalVotosCargo */
typedef struct TotalVotosCargo {
	ModuloBU_CodigoCargoConsulta_t	 codigoCargo;
	long	 ordemImpressao;
	struct TotalVotosCargo__votosVotaveis {
		A_SEQUENCE_OF(struct TotalVotosVotavel) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} votosVotaveis;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} TotalVotosCargo_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TotalVotosCargo;
extern asn_SEQUENCE_specifics_t asn_SPC_TotalVotosCargo_specs_1;
extern asn_TYPE_member_t asn_MBR_TotalVotosCargo_1[3];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "TotalVotosVotavel.h"

#endif	/* _TotalVotosCargo_H_ */
#include "asn_internal.h"
