/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ModuloBU"
 * 	found in "../../../asn/bu.asn1"
 * 	`asn1c -fline-refs -fcompound-names -fincludes-quoted`
 */

#include "TotalVotosCargo.h"

static int
memb_ordemImpressao_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 1L && value <= 99L)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

#if !defined(ASN_DISABLE_OER_SUPPORT)
static asn_oer_constraints_t asn_OER_memb_ordemImpressao_constr_3 CC_NOTUSED = {
	{ 1, 1 }	/* (1..99) */,
	-1};
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
static asn_per_constraints_t asn_PER_memb_ordemImpressao_constr_3 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 7,  7,  1,  99 }	/* (1..99) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
static asn_TYPE_member_t asn_MBR_votosVotaveis_4[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_TotalVotosVotavel,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_votosVotaveis_tags_4[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_votosVotaveis_specs_4 = {
	sizeof(struct TotalVotosCargo__votosVotaveis),
	offsetof(struct TotalVotosCargo__votosVotaveis, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_votosVotaveis_4 = {
	"votosVotaveis",
	"votosVotaveis",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_votosVotaveis_tags_4,
	sizeof(asn_DEF_votosVotaveis_tags_4)
		/sizeof(asn_DEF_votosVotaveis_tags_4[0]), /* 1 */
	asn_DEF_votosVotaveis_tags_4,	/* Same as above */
	sizeof(asn_DEF_votosVotaveis_tags_4)
		/sizeof(asn_DEF_votosVotaveis_tags_4[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_OF_constraint
	},
	asn_MBR_votosVotaveis_4,
	1,	/* Single element */
	&asn_SPC_votosVotaveis_specs_4	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_TotalVotosCargo_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct TotalVotosCargo, codigoCargo),
		-1 /* Ambiguous tag (CHOICE?) */,
		0,
		&asn_DEF_ModuloBU_CodigoCargoConsulta,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"codigoCargo"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct TotalVotosCargo, ordemImpressao),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_NativeInteger,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			&asn_OER_memb_ordemImpressao_constr_3,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			&asn_PER_memb_ordemImpressao_constr_3,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			memb_ordemImpressao_constraint_1
		},
		0, 0, /* No default value */
		"ordemImpressao"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct TotalVotosCargo, votosVotaveis),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_votosVotaveis_4,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"votosVotaveis"
		},
};
static const ber_tlv_tag_t asn_DEF_TotalVotosCargo_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_TotalVotosCargo_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 1, 0, 0 }, /* ordemImpressaoat 310 */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 2, 0, 0 }, /* votosVotaveisat 312 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 0, 0, 0 }, /* cargoConstitucionalat 205 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 0, 0, 0 } /* numeroCargoConsultaLivreat 207 */
};
asn_SEQUENCE_specifics_t asn_SPC_TotalVotosCargo_specs_1 = {
	sizeof(struct TotalVotosCargo),
	offsetof(struct TotalVotosCargo, _asn_ctx),
	asn_MAP_TotalVotosCargo_tag2el_1,
	4,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_TotalVotosCargo = {
	"TotalVotosCargo",
	"TotalVotosCargo",
	&asn_OP_SEQUENCE,
	asn_DEF_TotalVotosCargo_tags_1,
	sizeof(asn_DEF_TotalVotosCargo_tags_1)
		/sizeof(asn_DEF_TotalVotosCargo_tags_1[0]), /* 1 */
	asn_DEF_TotalVotosCargo_tags_1,	/* Same as above */
	sizeof(asn_DEF_TotalVotosCargo_tags_1)
		/sizeof(asn_DEF_TotalVotosCargo_tags_1[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_TotalVotosCargo_1,
	3,	/* Elements count */
	&asn_SPC_TotalVotosCargo_specs_1	/* Additional specs */
};

