/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ModuloBU"
 * 	found in "../../../asn/bu.asn1"
 * 	`asn1c -fline-refs -fcompound-names -fincludes-quoted`
 */

#ifndef	_TotalVotosVotavel_H_
#define	_TotalVotosVotavel_H_


#include "asn_application.h"

/* Including external dependencies */
#include "ModuloBU_TipoVoto.h"
#include "QtdEleitores.h"
#include "OCTET_STRING.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct IdentificacaoVotavel;

/* TotalVotosVotavel */
typedef struct TotalVotosVotavel {
	ModuloBU_TipoVoto_t	 tipoVoto;
	QtdEleitores_t	 quantidadeVotos;
	struct IdentificacaoVotavel	*identificacaoVotavel;	/* OPTIONAL */
	OCTET_STRING_t	 assinatura;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} TotalVotosVotavel_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TotalVotosVotavel;
extern asn_SEQUENCE_specifics_t asn_SPC_TotalVotosVotavel_specs_1;
extern asn_TYPE_member_t asn_MBR_TotalVotosVotavel_1[4];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "IdentificacaoVotavel.h"

#endif	/* _TotalVotosVotavel_H_ */
#include "asn_internal.h"
