/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ModuloBU"
 * 	found in "../../../asn/bu.asn1"
 * 	`asn1c -fline-refs -fcompound-names -fincludes-quoted`
 */

#include "TotalVotosVotavel.h"

asn_TYPE_member_t asn_MBR_TotalVotosVotavel_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct TotalVotosVotavel, tipoVoto),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ModuloBU_TipoVoto,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"tipoVoto"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct TotalVotosVotavel, quantidadeVotos),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_QtdEleitores,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"quantidadeVotos"
		},
	{ ATF_POINTER, 1, offsetof(struct TotalVotosVotavel, identificacaoVotavel),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_IdentificacaoVotavel,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"identificacaoVotavel"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct TotalVotosVotavel, assinatura),
		(ASN_TAG_CLASS_UNIVERSAL | (4 << 2)),
		0,
		&asn_DEF_OCTET_STRING,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"assinatura"
		},
};
static const int asn_MAP_TotalVotosVotavel_oms_1[] = { 2 };
static const ber_tlv_tag_t asn_DEF_TotalVotosVotavel_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_TotalVotosVotavel_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (4 << 2)), 3, 0, 0 }, /* assinaturaat 319 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 0, 0, 0 }, /* tipoVotoat 316 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 1, 0, 0 }, /* quantidadeVotosat 317 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 2, 0, 0 } /* identificacaoVotavelat 318 */
};
asn_SEQUENCE_specifics_t asn_SPC_TotalVotosVotavel_specs_1 = {
	sizeof(struct TotalVotosVotavel),
	offsetof(struct TotalVotosVotavel, _asn_ctx),
	asn_MAP_TotalVotosVotavel_tag2el_1,
	4,	/* Count of tags in the map */
	asn_MAP_TotalVotosVotavel_oms_1,	/* Optional members */
	1, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_TotalVotosVotavel = {
	"TotalVotosVotavel",
	"TotalVotosVotavel",
	&asn_OP_SEQUENCE,
	asn_DEF_TotalVotosVotavel_tags_1,
	sizeof(asn_DEF_TotalVotosVotavel_tags_1)
		/sizeof(asn_DEF_TotalVotosVotavel_tags_1[0]), /* 1 */
	asn_DEF_TotalVotosVotavel_tags_1,	/* Same as above */
	sizeof(asn_DEF_TotalVotosVotavel_tags_1)
		/sizeof(asn_DEF_TotalVotosVotavel_tags_1[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_TotalVotosVotavel_1,
	4,	/* Elements count */
	&asn_SPC_TotalVotosVotavel_specs_1	/* Additional specs */
};

