/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ModuloRegistroDigitalVoto"
 * 	found in "../../../asn/rdv.asn1"
 * 	`asn1c -fline-refs -fcompound-names -fincludes-quoted`
 */

#include "VotosCargo.h"

static asn_TYPE_member_t asn_MBR_votos_4[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_Voto,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_votos_tags_4[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_votos_specs_4 = {
	sizeof(struct VotosCargo__votos),
	offsetof(struct VotosCargo__votos, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_votos_4 = {
	"votos",
	"votos",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_votos_tags_4,
	sizeof(asn_DEF_votos_tags_4)
		/sizeof(asn_DEF_votos_tags_4[0]), /* 1 */
	asn_DEF_votos_tags_4,	/* Same as above */
	sizeof(asn_DEF_votos_tags_4)
		/sizeof(asn_DEF_votos_tags_4[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_OF_constraint
	},
	asn_MBR_votos_4,
	1,	/* Single element */
	&asn_SPC_votos_specs_4	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_VotosCargo_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct VotosCargo, idCargo),
		-1 /* Ambiguous tag (CHOICE?) */,
		0,
		&asn_DEF_ModuloRegistroDigitalVoto_CodigoCargoConsulta,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"idCargo"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct VotosCargo, quantidadeEscolhas),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_QuantidadeEscolhas,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"quantidadeEscolhas"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct VotosCargo, votos),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_votos_4,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"votos"
		},
};
static const ber_tlv_tag_t asn_DEF_VotosCargo_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_VotosCargo_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 1, 0, 0 }, /* quantidadeEscolhasat 268 */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 2, 0, 0 }, /* votosat 270 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 0, 0, 0 }, /* cargoConstitucionalat 181 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 0, 0, 0 } /* numeroCargoConsultaLivreat 183 */
};
asn_SEQUENCE_specifics_t asn_SPC_VotosCargo_specs_1 = {
	sizeof(struct VotosCargo),
	offsetof(struct VotosCargo, _asn_ctx),
	asn_MAP_VotosCargo_tag2el_1,
	4,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_VotosCargo = {
	"VotosCargo",
	"VotosCargo",
	&asn_OP_SEQUENCE,
	asn_DEF_VotosCargo_tags_1,
	sizeof(asn_DEF_VotosCargo_tags_1)
		/sizeof(asn_DEF_VotosCargo_tags_1[0]), /* 1 */
	asn_DEF_VotosCargo_tags_1,	/* Same as above */
	sizeof(asn_DEF_VotosCargo_tags_1)
		/sizeof(asn_DEF_VotosCargo_tags_1[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_VotosCargo_1,
	3,	/* Elements count */
	&asn_SPC_VotosCargo_specs_1	/* Additional specs */
};

