/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ModuloRegistroDigitalVoto"
 * 	found in "../../../asn/rdv.asn1"
 * 	`asn1c -fline-refs -fcompound-names -fincludes-quoted`
 */

#include "Voto.h"

asn_TYPE_member_t asn_MBR_Voto_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct Voto, tipoVoto),
		(ASN_TAG_CLASS_UNIVERSAL | (10 << 2)),
		0,
		&asn_DEF_ModuloRegistroDigitalVoto_TipoVoto,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"tipoVoto"
		},
	{ ATF_POINTER, 1, offsetof(struct Voto, digitacao),
		(ASN_TAG_CLASS_UNIVERSAL | (18 << 2)),
		0,
		&asn_DEF_VotoDigitado,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"digitacao"
		},
};
static const int asn_MAP_Voto_oms_1[] = { 1 };
static const ber_tlv_tag_t asn_DEF_Voto_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_Voto_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (10 << 2)), 0, 0, 0 }, /* tipoVotoat 261 */
    { (ASN_TAG_CLASS_UNIVERSAL | (18 << 2)), 1, 0, 0 } /* digitacaoat 262 */
};
asn_SEQUENCE_specifics_t asn_SPC_Voto_specs_1 = {
	sizeof(struct Voto),
	offsetof(struct Voto, _asn_ctx),
	asn_MAP_Voto_tag2el_1,
	2,	/* Count of tags in the map */
	asn_MAP_Voto_oms_1,	/* Optional members */
	1, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_Voto = {
	"Voto",
	"Voto",
	&asn_OP_SEQUENCE,
	asn_DEF_Voto_tags_1,
	sizeof(asn_DEF_Voto_tags_1)
		/sizeof(asn_DEF_Voto_tags_1[0]), /* 1 */
	asn_DEF_Voto_tags_1,	/* Same as above */
	sizeof(asn_DEF_Voto_tags_1)
		/sizeof(asn_DEF_Voto_tags_1[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_Voto_1,
	2,	/* Elements count */
	&asn_SPC_Voto_specs_1	/* Additional specs */
};

