/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ModuloRegistroDigitalVoto"
 * 	found in "../../../asn/rdv.asn1"
 * 	`asn1c -fline-refs -fcompound-names -fincludes-quoted`
 */

#ifndef	_VotosCargo_H_
#define	_VotosCargo_H_


#include "asn_application.h"

/* Including external dependencies */
#include "ModuloRegistroDigitalVoto_CodigoCargoConsulta.h"
#include "QuantidadeEscolhas.h"
#include "asn_SEQUENCE_OF.h"
#include "constr_SEQUENCE_OF.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct Voto;

/* VotosCargo */
typedef struct VotosCargo {
	ModuloRegistroDigitalVoto_CodigoCargoConsulta_t	 idCargo;
	QuantidadeEscolhas_t	 quantidadeEscolhas;
	struct VotosCargo__votos {
		A_SEQUENCE_OF(struct Voto) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} votos;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} VotosCargo_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_VotosCargo;
extern asn_SEQUENCE_specifics_t asn_SPC_VotosCargo_specs_1;
extern asn_TYPE_member_t asn_MBR_VotosCargo_1[3];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "Voto.h"

#endif	/* _VotosCargo_H_ */
#include "asn_internal.h"
